compute/instance: add different_cell scheduler hint
terraform-provider-openstack/terraform-provider-openstack pull request #1070
Opened 2020-09-21 13:57 UTC by cardoe

While the code base supported the target_cell scheduler hint to get
instances to build in a specified cell, there was no support to skip
cells if you were attempting to skip a specific cell.

2020-10-26 20:07 UTC, ozerovandrei requested changes
Looks good but needs to be rebased.

2020-10-30 13:48 UTC, cardoe commented
Thanks for the review. Rebased and should pass tests.

2020-11-01 14:36 UTC, ozerovandrei approved these changes

2020-11-01 14:36 UTC, merged

2020-11-03 19:13 UTC, cardoe commented
Thank you.