Moved global mutexKV to Config structure
terraform-provider-openstack/terraform-provider-openstack pull request #1078
Opened 2020-10-08 20:40 UTC by dkder3k

So this global mutex kv struct available everywhere in provider without
being a global variable.

For #1063

2020-10-09 12:13 UTC, ozerovandrei requested changes

2020-10-09 12:13 UTC, ozerovandrei commented on openstack/provider.go
> +// Config struct and contains a global MutexKV.
Can we rephrase it like: "Config contains auth parameters and also provides an instance of MutexKV." ?

2020-10-09 13:42 UTC, kayrus commented
According to #1058 let's just move the `github.com/hashicorp/terraform-plugin-sdk/helper/mutexkv` package under the https://github.com/gophercloud/utils/blob/master/terraform/auth/config.go

2020-10-09 15:01 UTC, dkder3k commented
@kayrus this will be done during next pr (after this one will be merged). The purpose of this pr is just to get rid of global variable for a mutex

2020-10-10 09:57 UTC, ozerovandrei approved these changes

2020-10-10 09:57 UTC, merged