Openstack Host Aggregates support
terraform-provider-openstack/terraform-provider-openstack pull request #1121
Opened 2020-12-24 10:27 UTC by rudexi

Support for Host Aggregates in Terraform.

This is useful for putting metadata on host aggregates.
For people using host aggregates for project separation (via a scheduler hint in the metadata), the hosts list information can also be used to auto-compute quotas.

2021-01-09 01:22 UTC, rudexi commented
I added the correct precheck to the test, so it now works properly with Openlab.

The integration testing runs as expected in my environment (Openstack Ussuri), when used with an admin account.
```
$env | grep OS_USERNAME
OS_USERNAME=admin

$make testacc TEST=./openstack TESTARGS="-run=TestAccComputeV2Aggregate -count=1"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./openstack -v -run=TestAccComputeV2Aggregate -count=1 -timeout 120m
=== RUN   TestAccComputeV2Aggregate
--- PASS: TestAccComputeV2Aggregate (3.97s)
PASS
ok      github.com/terraform-provider-openstack/terraform-provider-openstack/openstack  4.000s

$make testacc TEST=./openstack TESTARGS="-run=TestAccAggregateDataSource -count=1"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./openstack -v -run=TestAccAggregateDataSource -count=1 -timeout 120m
=== RUN   TestAccAggregateDataSource
--- PASS: TestAccAggregateDataSource (4.70s)
PASS
ok      github.com/terraform-provider-openstack/terraform-provider-openstack/openstack  4.739s
```

2021-01-09 13:07 UTC, ozerovandrei requested changes

2021-01-09 13:07 UTC, ozerovandrei commented on openstack/resource_openstack_compute_aggregate_v2_test.go
> +	"strconv"
Could you please group stdlib packages on top here also?

2021-01-09 13:07 UTC, ozerovandrei commented on openstack/resource_openstack_compute_aggregate_v2.go
> +				Type:     schema.TypeList,
Are you sure about using `TypeList` here? Terraform will create plan difference in case of changing hosts ordering on API side. Also hosts should be unique as well as I know. What about using `TypeSet` for this argument?

2021-01-12 00:49 UTC, rudexi commented on openstack/data_source_openstack_compute_aggregate_v2.go
> +	"strconv"
Done

2021-01-12 00:50 UTC, rudexi commented on openstack/resource_openstack_compute_aggregate_v2.go
> +			},
Actually added it after the `zone` field. If I understand correctly you separate the `Computed`/`Optional` from the `Required` in resources?

2021-01-12 00:51 UTC, rudexi commented on openstack/resource_openstack_compute_aggregate_v2.go
> +				Optional: true,
Done

2021-01-12 00:51 UTC, rudexi commented on openstack/resource_openstack_compute_aggregate_v2_test.go
> +	"strconv"
Done

2021-01-12 00:53 UTC, rudexi commented on openstack/resource_openstack_compute_aggregate_v2.go
> +				Type:     schema.TypeList,
Done. I didn't know `TypeSet` could be used like this, since the official documentation doesn't give many examples, so I opted for `TypeList` thinking it was the only way to provide a simple array of string as input (instead of blocks).

2021-01-12 00:54 UTC, rudexi commented on openstack/data_source_openstack_compute_aggregate_v2.go
> +			},
Done

2021-01-12 17:15 UTC, ozerovandrei requested changes

2021-01-12 17:15 UTC, ozerovandrei commented on openstack/data_source_openstack_compute_aggregate_v2.go
> +			},
I meant adding a blank separator line between all arguments: "zone", "metadata", "hosts".

2021-01-12 17:15 UTC, ozerovandrei commented on openstack/resource_openstack_compute_aggregate_v2.go
> +			},
For the most resources and datasources we use a blank line separator between every argument/attribute block in this provider. I propose to keep it that way.

2021-01-12 17:15 UTC, ozerovandrei commented on openstack/resource_openstack_compute_aggregate_v2.go
> +		hostsToDelete := arrayDifference(oldHosts, newHosts)
You don't need a new function after changing type to `TypeSet` since there is a built-in function.

You can check the example of usage: https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/master/openstack/resource_openstack_keymanager_container_v1.go#L253

2021-01-14 02:15 UTC, rudexi commented on openstack/resource_openstack_compute_aggregate_v2.go
> +		hostsToDelete := arrayDifference(oldHosts, newHosts)
Thank you for the suggestion. Changed and tested.

2021-01-14 02:16 UTC, rudexi commented on openstack/resource_openstack_compute_aggregate_v2.go
> +			},
Got it, added a newline between all arguments/attributes

2021-01-14 02:25 UTC, rudexi commented
I added some test to cover hypervisor when given one through environment variables.
Here is the result in my local environment:
```
$make fmt && make testacc TEST=./openstack TESTARGS="-run=TestAccAggregateDataSource -count=1"
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./openstack -v -run=TestAccAggregateDataSource -count=1 -timeout 120m
=== RUN   TestAccAggregateDataSource
--- PASS: TestAccAggregateDataSource (4.68s)
=== RUN   TestAccAggregateDataSourceWithHypervisor
--- PASS: TestAccAggregateDataSourceWithHypervisor (7.37s)
PASS
ok      github.com/terraform-provider-openstack/terraform-provider-openstack/openstack  12.087s

$make fmt && make testacc TEST=./openstack TESTARGS="-run=TestAccComputeV2Aggregate -count=1"
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./openstack -v -run=TestAccComputeV2Aggregate -count=1 -timeout 120m
=== RUN   TestAccComputeV2Aggregate
--- PASS: TestAccComputeV2Aggregate (3.56s)
=== RUN   TestAccComputeV2AggregateWithHypervisor
--- PASS: TestAccComputeV2AggregateWithHypervisor (10.02s)
PASS
ok      github.com/terraform-provider-openstack/terraform-provider-openstack/openstack  13.620s
```

Since I caught several errors on the `hosts` and `metadata` fields updates, I corrected it and made sure to catch it with tests.

2021-01-14 18:03 UTC, ozerovandrei requested changes

2021-01-14 18:03 UTC, ozerovandrei commented on openstack/resource_openstack_compute_aggregate_v2.go
> +func mapNullFix(oldMap, newMap map[string]interface{}) (output map[string]interface{}) {
Could you please move this function in https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/master/openstack/util.go file since we have some common utils there.

I also think that we can use another name instead of `mapNullFix` since it can be used by other resources in the future if needed. What about `mapDiffWithNilKeys` or something like that?

Apart from it this PR looks good 👍

2021-01-15 05:47 UTC, rudexi commented on openstack/resource_openstack_compute_aggregate_v2.go
> +func mapNullFix(oldMap, newMap map[string]interface{}) (output map[string]interface{}) {
Done. Also added a unit test for the function

2021-01-15 05:57 UTC, ozerovandrei approved these changes
LGTM

Thank you @rudexi

2021-01-15 05:57 UTC, merged