Hypervisor data source support
terraform-provider-openstack/terraform-provider-openstack pull request #1126
Opened 2021-01-09 01:31 UTC by rudexi

Support for Hypervisor data source.

Due to the nature of hypervisors (only LIST is available in the API), it's only possible to make data sources for hypervisors.
This data source aim is to provide information about cpu/memory/disk, so it's possible to auto-calculate quotas by listing every hypervisors in the system.

This backend is, as far as I know, only available for the admin user, so the test is restricted accordingly.

2021-01-09 13:12 UTC, ozerovandrei requested changes

2021-01-09 13:12 UTC, ozerovandrei commented on openstack/data_source_openstack_compute_hypervisor_v2.go
> +			},
Could you please separate attributes with a blank line?

2021-01-12 00:49 UTC, rudexi commented on openstack/data_source_openstack_compute_hypervisor_v2.go
> +			},
Done

2021-01-12 17:16 UTC, ozerovandrei requested changes

2021-01-12 17:16 UTC, ozerovandrei commented on openstack/data_source_openstack_compute_hypervisor_v2.go
> +			},
I propose to add a blank line separator the same way as https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1121#discussion_r555937346

2021-01-14 17:46 UTC, ozerovandrei approved these changes
LGTM

2021-01-14 17:46 UTC, merged