Add resource identity_user_membership_v3
terraform-provider-openstack/terraform-provider-openstack pull request #1149
Opened 2021-01-29 11:21 UTC by nikParasyr

Add support for new resources indentity_user_membership_v3.
The resources is used to add users to groups.

Close #1142 

Related gophercloud resources:
- https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/users/requests.go#L288
- https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/users/requests.go#L298
- https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/users/requests.go#L313

2021-01-29 17:43 UTC, kayrus requested changes
Very good for the first time. I'd request to add an import test for this resource. See [here](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/d61260067ef0e3b326bb905f7535515b0343c012/openstack/import_openstack_identity_user_v3_test.go) for example.

2021-01-29 17:43 UTC, kayrus commented on openstack/resource_openstack_identity_user_membership_v3.go
> +		return CheckDeleted(d, err, "Error parsing user membership ID")
Could you please follow the resource name patter in error/log messages? e.g. [here](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/d61260067ef0e3b326bb905f7535515b0343c012/openstack/resource_openstack_identity_user_v3.go#L148)

2021-01-29 17:43 UTC, kayrus commented on website/docs/r/identity_user_membership_v3.html.markdown
> +    Changing this creates a new user membership.
Please remove two redundant whitespaces in this section

2021-01-29 17:43 UTC, kayrus commented on website/docs/r/identity_user_membership_v3.html.markdown
> +    Changing this creates a new user membership.
And here too.

2021-01-29 18:55 UTC, nikParasyr commented on openstack/resource_openstack_identity_user_membership_v3.go
> +		return CheckDeleted(d, err, "Error parsing user membership ID")
Thanks :)
Added import test.
Fixed error/log messages

2021-01-29 18:55 UTC, nikParasyr commented on website/docs/r/identity_user_membership_v3.html.markdown
> +    Changing this creates a new user membership.
fixed

2021-01-29 18:55 UTC, nikParasyr commented on website/docs/r/identity_user_membership_v3.html.markdown
> +    Changing this creates a new user membership.
fixed

2021-01-29 19:13 UTC, kayrus commented
LGTM @ozerovandrei can you review this PR?

2021-01-29 19:13 UTC, kayrus approved these changes

2021-01-31 16:24 UTC, ozerovandrei approved these changes
LGTM

2021-01-31 16:25 UTC, merged