Image: add basic auth support to download source image
terraform-provider-openstack/terraform-provider-openstack pull request #1157
Opened 2021-02-01 01:47 UTC by pierrchen

2021-02-01 06:52 UTC, kayrus commented
@pierrchen thanks for the PR. Did you try to set a password in a URL, e.g. `https://username:password@example.com/file.img`?

2021-02-01 23:42 UTC, pierrchen commented
@kayrus  It doesn't seems work for me and if the password contains an `@` the url became invalid. Is that expected to be a legit way to set the basic Auth for you?

2021-02-02 07:06 UTC, kayrus commented
According to https://github.com/golang/go/issues/24572 it should work. What kind of error do you receive?

2021-02-02 07:16 UTC, kayrus commented
See also https://golang.org/src/net/http/client.go#L239
https://golang.org/pkg/net/url/#Userinfo
Go automatically parses Username and Password from the URL.

2021-02-03 00:28 UTC, pierrchen commented
@kayrus sorry, I made some mistake in my experiment and I can confirm (with a standalone go programe) putting user name and password in url do works (even with `@` in the password - `curl` will complain about this).

However, I have some questions:

1. Do you think provide separate `username` and `password` will be better alternative? IMO having the url and password in the URL is a bad practice and will cause some confusions especially in the Terraform user cases I will mention below.
2. If we have the credential in the url, when credential changes, does Terraform consider it is a new resource and thus take actions it shouldn't?
3. Putting credential in the url, will cause the url to be sensitive, and thus be mask out in the `plan` output, which make it hard for review, say if the url is correctly set.

And in either case, we need additional check the response status, since an non-2xx response won't cause error be return, and thus it will an error json file be uploaded as an image.

Let me know how you want to proceed:
A. Have separate user name and password config as this patch does.
B. Putting url and password in the url, but add the response error check.

Thanks,

2021-02-03 00:30 UTC, pierrchen commented on openstack/images_image_v2.go
> +
@kayrus  this is the required error check I mentioned.

2021-02-03 23:54 UTC, pierrchen commented
@ozerovandrei would you like to have a review on this? thanks

2021-02-04 07:32 UTC, kayrus requested changes
> Do you think provide separate username and password will be better alternative? IMO having the url and password in the URL is a bad practice and will cause some confusions especially in the Terraform user cases I will mention below.

Yes, I agree.

> If we have the credential in the url, when credential changes, does Terraform consider it is a new resource and thus take actions it shouldn't?

Yes it will consider it as a new resource.

> Putting credential in the url, will cause the url to be sensitive, and thus be mask out in the plan output, which make it hard for review, say if the url is correctly set.

Agree. See my comments.

> And in either case, we need additional check the response status, since an non-2xx response won't cause error be return, and thus it will an error json file be uploaded as an image.

Agree.

> A. Have separate user name and password config as this patch does.
> B. Putting url and password in the url, but add the response error check.

Both is fine.

2021-02-04 07:32 UTC, kayrus commented on openstack/images_image_v2.go
> +			client := http.DefaultClient
I'd prefer to use the provider's http client. In future we will control it's transport timeouts.

2021-02-04 07:32 UTC, kayrus commented on openstack/resource_openstack_images_image_v2.go
> +				ForceNew:      true,
Add `Sensitive: true` flag.

2021-02-04 07:32 UTC, kayrus commented on website/docs/r/images_image_v2.html.markdown
> +* `image_source_password` - (Optional) The password of basic auth to download `image_source_url`.
Add a note that a password will be kept in a plain text. See https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/7a0e3834382cde6e494cc14c6ebc1adc5aba623b/website/docs/r/identity_application_credential_v3.html.markdown#L13 for example

2021-02-04 07:32 UTC, kayrus commented on openstack/resource_openstack_images_image_v2.go
> +				ForceNew:      true,
ForceNew will recreate a previous image, when the credentials are changed.

2021-02-04 07:32 UTC, kayrus commented on openstack/resource_openstack_images_image_v2.go
> +				ForceNew:      true,
ForceNew will recreate a previous image, when the credentials are changed.

2021-02-05 00:18 UTC, pierrchen commented on openstack/images_image_v2.go
> +			client := http.DefaultClient
will do.

2021-02-05 00:27 UTC, pierrchen commented on openstack/resource_openstack_images_image_v2.go
> +				ForceNew:      true,
done.

2021-02-05 00:27 UTC, pierrchen commented on website/docs/r/images_image_v2.html.markdown
> +* `image_source_password` - (Optional) The password of basic auth to download `image_source_url`.
done.

2021-02-05 01:00 UTC, pierrchen commented on openstack/resource_openstack_images_image_v2.go
> +				ForceNew:      true,
done

2021-02-05 01:41 UTC, pierrchen commented
Not familiar with how to interpreter the acceptance test failure so not sure if it is related with the my change or it is false positive?

2021-02-05 07:25 UTC, kayrus requested changes

2021-02-05 07:25 UTC, kayrus commented on website/docs/r/images_image_v2.html.markdown
> +* `image_source_password` - (Optional) The password of basic auth to download `image_source_url`.
Please use a special syntax at the beginning of the doc like in the example.

2021-02-05 07:25 UTC, kayrus commented on openstack/images_image_v2.go
> +			client := &http.Client{}
you haven't used the provider's http client. You need to pass the `imageClient` pointer to the func, then re-use its client like:
```suggestion
			client := serviceClient.ProviderClient.HTTPClient
```

2021-02-05 08:24 UTC, pierrchen commented
Not entirely sure about this [comments](https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1157#discussion_r570765797) and it was marked as resolved so I didn't make any change. Let me know if I should.

2021-02-05 08:25 UTC, pierrchen commented on openstack/images_image_v2.go
> +			client := &http.Client{}
done.

2021-02-05 08:54 UTC, kayrus commented on website/docs/r/images_image_v2.html.markdown
> +   Warning: the password will be stored in the Terraform state as plain-text.
Please use the syntax below and put it in top.

```
~> **Note:** All arguments including the source image URL password will be
stored in the raw state as plain-text. [Read more about sensitive data in
state](https://www.terraform.io/docs/language/state/sensitive-data.html).
```

2021-02-05 09:24 UTC, pierrchen commented on website/docs/r/images_image_v2.html.markdown
> +   Warning: the password will be stored in the Terraform state as plain-text.
done

2021-02-05 17:31 UTC, kayrus approved these changes
LGTM
Let's wait for openlab issues to be fixed.

2021-02-07 04:08 UTC, jeblair commented
recheck

2021-02-08 09:57 UTC, merged

2021-02-08 09:57 UTC, kayrus commented
@pierrchen merged, thank you