openstack_lb_loadbalancer_v2: vip_port_id can be set for octavia
terraform-provider-openstack/terraform-provider-openstack pull request #1164
Opened 2021-02-05 12:56 UTC by nikParasyr

Part of https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1090

This PR makes possible to define vip_port_id when creating a loadbalancer using octavia only. vip_port_id cannot be defined by user on neutron LBaaS

2021-02-05 16:44 UTC, nikParasyr commented
openlab has been failing on gophercloud as well so it might be related to the upgrade to focal

2021-02-05 17:26 UTC, kayrus commented
Tests run on bionic. See https://github.com/theopenlab/openlab/issues/681 for details.

2021-02-07 04:08 UTC, jeblair commented
recheck

2021-02-08 16:55 UTC, ozerovandrei requested changes

2021-02-08 16:55 UTC, ozerovandrei commented on openstack/resource_openstack_lb_loadbalancer_v2_test.go
> +					testAccCheckLBV2LoadBalancerExists("openstack_lb_loadbalancer_v2.loadbalancer_1", &lb),
It's better to also add `resource.TestCheckResourceAttr()` check here.

2021-02-09 17:34 UTC, nikParasyr commented on openstack/resource_openstack_lb_loadbalancer_v2_test.go
> +					testAccCheckLBV2LoadBalancerExists("openstack_lb_loadbalancer_v2.loadbalancer_1", &lb),
done

2021-02-10 06:08 UTC, ozerovandrei approved these changes

2021-02-10 06:08 UTC, merged