Add a service_catalog attribute to identity_auth_scope_v3 data
terraform-provider-openstack/terraform-provider-openstack pull request #1167
Opened 2021-02-06 18:48 UTC by jeblair

Keystone returns a service catalog along with the auth token.  That provides
useful information such as service endpoint URLs which may not otherwise be
available.  This change adds the service catalog to the
identity_auth_scope_v3 data source.

2021-02-06 19:32 UTC, emonty approved these changes
Exposing the service catalog is a great idea.

2021-02-06 22:08 UTC, jeblair commented
Test failure is unrelated to this patch; tracking in https://github.com/theopenlab/openlab/issues/681

2021-02-07 01:17 UTC, jeblair commented
recheck

2021-02-07 09:17 UTC, kayrus requested changes
Thank you. This is a really nice feature. I'd appreciate if you add a couple of examples on how to use it in documentation examples.

2021-02-07 09:17 UTC, kayrus commented on openstack/identity_auth_scope_v3.go
> +func flattenIdentityAuthScopeV3ServiceCatalog(catalog tokens3.ServiceCatalog) []map[string]interface{} {
can you pass the pointer here?
```suggestion
func flattenIdentityAuthScopeV3ServiceCatalog(catalog *tokens3.ServiceCatalog) []map[string]interface{} {
```

2021-02-08 17:52 UTC, kayrus commented on openstack/data_source_openstack_identity_auth_scope_v3.go
> +		flatCatalog := flattenIdentityAuthScopeV3ServiceCatalog(*catalog)
```suggestion
		flatCatalog := flattenIdentityAuthScopeV3ServiceCatalog(catalog)
```

2021-02-09 00:43 UTC, jeblair commented on openstack/identity_auth_scope_v3.go
> +func flattenIdentityAuthScopeV3ServiceCatalog(catalog tokens3.ServiceCatalog) []map[string]interface{} {
Done.

2021-02-09 00:43 UTC, jeblair commented on openstack/data_source_openstack_identity_auth_scope_v3.go
> +		flatCatalog := flattenIdentityAuthScopeV3ServiceCatalog(*catalog)
Done.

2021-02-09 00:45 UTC, jeblair commented
> Thank you. This is a really nice feature. I'd appreciate if you add a couple of examples on how to use it in documentation examples.

Of course.  The data structure isn't easy to navigate, and I'm new to HCL, so I don't know if there's a more efficient way to do it, but I added the code I'll be using for my use case, which is getting the public swift url.  Please let me know if there's a nicer way to do that; I won't be offended at all!  :)

2021-02-09 15:08 UTC, jeblair commented
recheck

2021-02-09 22:17 UTC, jeblair commented
recheck

2021-02-10 06:10 UTC, ozerovandrei commented
Could you please rebase on main since there are fixes for acceptance tests.

2021-02-11 14:25 UTC, jeblair commented
> Could you please rebase on main? There are fixes for acceptance tests.

Done!

2021-02-13 14:31 UTC, ozerovandrei approved these changes
LGTM

2021-02-13 14:31 UTC, merged