Add resource openstack_lb_quota_v2
terraform-provider-openstack/terraform-provider-openstack pull request #1169
Opened 2021-02-06 19:50 UTC by nikParasyr

Close #1168 

Adds support for octavia quota.

In my understanding this cannot be implemented for neutron LBaaS

2021-02-06 19:56 UTC, nikParasyr commented
Some notes
- Not sure if im handling microversions correctly. L7_rule and l7_policy were added in 2.19 as seen [here](https://github.com/openstack/octavia/blob/master/octavia/api/root_controller.py#L124). and also how to have acceptance tests it in different microversions (if that is required).
- In my understanding this is not implemented in neutron LBaas that is why i return error if not `use_octavia`
- I haven't added `region` as a attribute but maybe I should(?). If this is the case should I also append it in the resource id to avoid future issues such as https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1104?

2021-02-07 04:06 UTC, jeblair commented
recheck https://github.com/theopenlab/openlab/issues/681

2021-02-07 04:07 UTC, jeblair commented
recheck
https://github.com/theopenlab/openlab/issues/681

2021-02-07 04:07 UTC, jeblair commented
recheck

2021-02-09 19:13 UTC, nikParasyr commented
recheck lbaas

2021-02-10 06:17 UTC, ozerovandrei commented
> I haven't added region as a attribute but maybe I should(?). If this is the case should I also append it in the resource id to avoid future issues such as #1104?

I think that region is needed since there can be different quota for a single project in different regions.
Adding it in ID is fine. I think we can then do a refactoring of the existing quota resources in a similar way.

2021-02-11 13:12 UTC, nikParasyr commented
@ozerovandrei Added region as an attribute and also appended on the resource ID.

2021-02-13 16:10 UTC, ozerovandrei requested changes

2021-02-13 16:10 UTC, ozerovandrei commented on website/docs/r/lb_quota_v2.html.markdown
> +Manages a V3 block storage quota resource within OpenStack.
Not `V3 block storage quota` 😉

2021-02-13 16:10 UTC, ozerovandrei commented on openstack/resource_openstack_lb_quota_v2.go
> +func parseLBQuotaID(id string) (string, string, error) {
Could you move this function to file with other helpers https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/lb_v2_shared.go and implement an unit test for it.

2021-02-15 08:53 UTC, nikParasyr commented on website/docs/r/lb_quota_v2.html.markdown
> +Manages a V3 block storage quota resource within OpenStack.
:innocent: fixed :)

2021-02-15 08:54 UTC, nikParasyr commented on openstack/resource_openstack_lb_quota_v2.go
> +func parseLBQuotaID(id string) (string, string, error) {
done as well

2021-02-20 09:50 UTC, ozerovandrei approved these changes
LGTM

2021-02-20 09:50 UTC, merged