Add new resource blockstorage_volume_type_access_v3
terraform-provider-openstack/terraform-provider-openstack pull request #1223
Opened 2021-04-05 09:57 UTC by nikParasyr

Close #1202

2021-04-05 12:07 UTC, nikParasyr commented
recheck

2021-04-06 06:00 UTC, nikParasyr commented
@ozerovandrei any idea why the admin job is not run? :thinking:

2021-04-06 14:06 UTC, ozerovandrei commented
recheck

2021-04-06 14:07 UTC, ozerovandrei commented
@nikParasyr no. Maybe some error on the OpenLab side?

2021-04-07 11:09 UTC, nikParasyr commented
recheck

2021-04-07 15:04 UTC, nikParasyr commented
i did check a bit for any changes, any logs or something to indicate the reason. Tried to contact the openlab people on IRC but nothing in response. i'll check a bit more later this week

2021-04-08 07:12 UTC, nikParasyr commented
recheck

2021-04-12 01:35 UTC, bzhaoopenstack commented
recheck

2021-04-12 07:04 UTC, nikParasyr commented
recheck

2021-04-12 09:29 UTC, nikParasyr commented
@ozerovandrei pipeline was fixed with help of openlab guys. This is ready from my side

2021-04-14 05:44 UTC, ozerovandrei requested changes

2021-04-14 05:44 UTC, ozerovandrei commented on openstack/resource_openstack_blockstorage_volume_type_access_v3_test.go
> +    resource "openstack_identity_project_v3" "project_1" {
Bad indent

2021-04-14 05:44 UTC, ozerovandrei commented on website/docs/r/blockstorage_volume_type_access_v3.html.markdown
> +    }
Bad indent

2021-04-15 19:15 UTC, ozerovandrei approved these changes
LGTM

2021-04-15 19:15 UTC, merged