Update: enable OS_DEBUG
terraform-provider-openstack/terraform-provider-openstack pull request #1246
Opened 2021-05-13 13:40 UTC by till

- when TF_LOG is debug/trace
 - enable this by default (person probably wants it)

Resolves: terraform-provider-openstack/terraform-provider-openstack#1203

2021-05-22 12:33 UTC, ozerovandrei requested changes

2021-05-22 12:33 UTC, ozerovandrei commented on openstack/provider.go
> +	// enforce OS_DEBUG when TF_LOG is 'DEBUG' or 'TRACE'
The idea is nice but I don't like the implementation when we rewrite some environment variables in the system to change the behaviour of the `gophercloud/utils` library.

I think that we need to configure `logger` in that library when we have `DEBUG` or `TRACE` loglevel.

https://github.com/gophercloud/utils/blob/master/terraform/auth/config.go#L182

There should be a way to configure it. Or maybe we need a PR to `gophercloud/utils` to configure logger (or using `&osClient.DefaultLogger{}` programmatically, without dealing with env variables.

2021-05-22 14:38 UTC, till commented on openstack/provider.go
> +	// enforce OS_DEBUG when TF_LOG is 'DEBUG' or 'TRACE'
I didn't think I was "rewriting" it as I am setting it when it's not set. But I'll have a look.

2021-05-22 15:22 UTC, till commented on openstack/provider.go
> +	// enforce OS_DEBUG when TF_LOG is 'DEBUG' or 'TRACE'
@ozerovandrei I made a PR over there: gophercloud/utils#153 — is this what you were thinking? I am not sure what the release cycle is, but I can re-work this PR when there is a release?

2021-06-03 09:46 UTC, till commented on openstack/provider.go
> +	// enforce OS_DEBUG when TF_LOG is 'DEBUG' or 'TRACE'
@ozerovandrei Can I just update the dependency in this PR?

2021-06-05 06:31 UTC, ozerovandrei commented on openstack/provider.go
> +	// enforce OS_DEBUG when TF_LOG is 'DEBUG' or 'TRACE'
Sure, you can update the dependency here.

2021-06-05 12:54 UTC, till commented on openstack/provider.go
> +	// enforce OS_DEBUG when TF_LOG is 'DEBUG' or 'TRACE'
@ozerovandrei reworked my approach, rebased and then also updated `gophercloud/utils` with `go get github.com/gophercloud/utils@latest`. Can you have a look again?

2021-06-05 13:33 UTC, till commented
On both builds, `devstack` fails on `ubuntu-bionic`:

```
2021-06-05 13:04:36.324892 | ubuntu-bionic | + echo 'Running devstack'
2021-06-05 13:04:36.324965 | ubuntu-bionic | Running devstack
2021-06-05 13:04:36.324977 | ubuntu-bionic | + echo '... this takes 10 - 15 minutes (logs in logs/devstacklog.txt.gz)'
2021-06-05 13:04:36.324987 | ubuntu-bionic | ... this takes 10 - 15 minutes (logs in logs/devstacklog.txt.gz)
2021-06-05 13:04:36.325106 | ubuntu-bionic | ++ date +%s
2021-06-05 13:04:36.326529 | ubuntu-bionic | + start=1622898276
2021-06-05 13:04:36.326555 | ubuntu-bionic | + /tmp/ansible/bin/ansible primary -f 5 -i /home/zuul/workspace/inventory -m shell -a 'cd '\''/opt/stack/new/devstack'\'' && sudo -H -u stack DSTOOLS_VERSION=0.4.0 stdbuf -oL -eL ./stack.sh 2>&1 executable=/bin/bash'
2021-06-05 13:04:40.083227 | ubuntu-bionic | ERROR: the main setup script run by this job failed - exit code: 2
2021-06-05 13:04:40.083324 | ubuntu-bionic |     please look at the relevant log files to determine the root cause
2021-06-05 13:04:40.083339 | ubuntu-bionic | Running devstack worlddump.py
2021-06-05 13:04:41.251973 | ubuntu-bionic | Cleaning up host
2021-06-05 13:04:41.252030 | ubuntu-bionic | ... this takes 3 - 4 minutes (logs at logs/devstack-gate-cleanup-host.txt.gz)
2021-06-05 13:05:08.322827 | ubuntu-bionic |  [WARNING]: No hosts matched, nothing to do
2021-06-05 13:05:11.342189 | ubuntu-bionic | Done.
2021-06-05 13:05:12.925314 | ubuntu-bionic | *** FAILED with status: 2
2021-06-05 13:05:23.455488 | ubuntu-bionic | ERROR
2021-06-05 13:05:23.455854 | ubuntu-bionic | {
2021-06-05 13:05:23.455951 | ubuntu-bionic |   "delta": "0:04:04.849504",
2021-06-05 13:05:23.456039 | ubuntu-bionic |   "end": "2021-06-05 13:05:12.926319",
2021-06-05 13:05:23.456106 | ubuntu-bionic |   "msg": "non-zero return code",
2021-06-05 13:05:23.456173 | ubuntu-bionic |   "rc": 2,
2021-06-05 13:05:23.456238 | ubuntu-bionic |   "start": "2021-06-05 13:01:08.076815"
2021-06-05 13:05:23.456303 | ubuntu-bionic | }
2021-06-05 13:05:23.497499 | 
2021-06-05 13:05:23.497616 | PLAY RECAP
2021-06-05 13:05:23.497718 | ubuntu-bionic | ok: 16 changed: 13 unreachable: 0 failed: 1 skipped: 15 rescued: 0 ignored: 1
```

Probably (hopefully) not related.

I had a look though:
https://logs.openlabtesting.org/logs/46/1246/5c77f96edec77bde7a3d76609a559177183198d4/check/terraform-provider-openstack-acceptance-test-admin/e9b5f2f/logs/devstack-gate-cleanup-host.txt

I can't tell exactly where it fails, so there is a `command not found` in the middle and it's `grep`'ing for too many things that don't exist. Nothing looks related to what I did. 🤷🏼

2021-06-07 19:58 UTC, ozerovandrei commented on openstack/provider.go
> +			"enable_logging": {
Do we really need a new argument here?
Terraform SDK already provides us with the standard `TF_LOG` env variable. It seems that setting additional logging when `TF_LOG` is `DEBUG` or `TRACE` is enough.

2021-06-07 20:00 UTC, ozerovandrei commented on openstack/provider.go
> +	if !enable_logging {
It's better to use mixed caps instead of underscore https://golang.org/doc/effective_go#mixed-caps

2021-06-21 08:31 UTC, till commented on openstack/provider.go
> +			"enable_logging": {
I would add it for "good" style. E.g. for testability and also in case I want to invoke this directly without the binary.

So environment variables don't bleed into the code. But I can adjust if you feel strongly.

2021-06-29 09:30 UTC, ozerovandrei commented on openstack/provider.go
> +			"enable_logging": {
Yeah, makes sense to add it in that case.

2021-06-29 12:14 UTC, frittentheke commented
@till this is really a nice feature. 
Could you maybe rebase this once more and work in the changes @ozerovandrei asked for?

2021-06-29 12:17 UTC, till commented
@frittentheke yes, will do — I hope I get to it all by Friday or earlier. Maybe during the ⚽  game tonight. :D

2021-07-27 11:51 UTC, till commented
@frittentheke @ozerovandrei hope I addressed everything. Let me know!

2021-08-03 12:29 UTC, till commented
Can anyone take a look? 👀

2021-08-04 15:58 UTC, frittentheke commented
> Can anyone take a look? eyes

Sorry @till for picking this up just now and thanks for keeping at it!

I tested the provider and things work just as expected.

But you are lacking the change to go.mod (bumping the dependency to github.com/gophercloud/utils containing your MR https://github.com/gophercloud/utils/pull/153) ... I pulled in latest and it should look like this:

```
diff --git a/go.mod b/go.mod
index 0f37754e..711ddf1d 100644
--- a/go.mod
+++ b/go.mod
@@ -4,7 +4,7 @@ go 1.15
 
 require (
        github.com/gophercloud/gophercloud v0.17.1-0.20210517213536-0be823b69be8
-       github.com/gophercloud/utils v0.0.0-20210216074907-f6de111f2eae
+       github.com/gophercloud/utils v0.0.0-20210720165645-8a3ad2ad9e70
        github.com/hashicorp/terraform-plugin-sdk v1.17.2
        github.com/mitchellh/go-homedir v1.1.0
        github.com/stretchr/testify v1.7.0
```

2021-08-09 13:09 UTC, till commented
@frittentheke Sorry, probably screwed up my rebase. Will fix.

2022-01-21 15:33 UTC, frittentheke commented
@till I just remembered this PR when digging into an issue (https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1307).

Could you maybe get this change rebased to finally close https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1203 ?

2022-01-23 16:43 UTC, till commented
@frittentheke I tried my best to rebase it again. Can you or anyone else see if this can get integrated soon? Otherwise, feel free to pick the commits from my fork. I am also happy if this lands in the official code and I can stop patching it. :)

2022-01-24 13:19 UTC, frittentheke commented
@ozerovandrei could you kindly take an other look at this. I quite like the change and usually do exactly that manually anyways.

2022-02-01 08:44 UTC, till commented
@ozerovandrei sorry to bug, but can you take a look this week? Or is there someone else who can?

2022-02-06 16:37 UTC, ozerovandrei approved these changes
LGTM thank you @till

2022-02-06 16:37 UTC, merged

2022-02-06 16:37 UTC, till commented
Thanks very much!