Add nil check to server group hint creation
terraform-provider-openstack/terraform-provider-openstack pull request #1248
Opened 2021-05-18 18:54 UTC by jhg03a

I ran into a provider panic while trying to unassign a server group from a server.  By deferring to the default behavior, the nil check is sufficient to effectively unassign a server group.

2021-05-18 19:14 UTC, jhg03a commented
The test failures appear to be unrelated to the change itself but rather constructing the devstack.

2021-05-22 12:17 UTC, ozerovandrei requested changes

2021-05-22 12:17 UTC, ozerovandrei commented on openstack/resource_openstack_compute_instance_v2.go
> +		m := v.(map[string]interface{})
I guess it's better not to nest all the logic under a single `if {}` and we can also cast just a single time like this:
```go
m, ok := v.(map[string]interface{})
if !ok {
  return hashcode.String(buf.String())
}
if m == nil {
  return hashcode.String(buf.String())
}

// other stuff

return hashcode.String(buf.String())
```

2021-05-24 19:14 UTC, jhg03a commented on openstack/resource_openstack_compute_instance_v2.go
> +		m := v.(map[string]interface{})
Addressed with commit

2021-05-24 22:03 UTC, jhg03a commented
The CI failures appear to be unrelated to the change not being able to find a golang compiler.

2021-05-26 15:54 UTC, ozerovandrei commented
@jhg03a could you please also resolve `golangci-lint` issue?
I can merge this without `openlab/check` since those changes looks safe.

2021-06-29 09:24 UTC, ozerovandrei approved these changes
LGTM but we need tests to be fixed first #1253

2021-06-29 15:45 UTC, jhg03a commented
Those acceptance test failures are not related to the PR, but rather https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1253

2021-07-05 16:55 UTC, nikParasyr commented
recheck

2021-07-08 06:21 UTC, ozerovandrei approved these changes

2021-07-08 06:21 UTC, merged