Add SUDO_PROJECT_ID for openstack_dns_recordset_v2
terraform-provider-openstack/terraform-provider-openstack pull request #1254
Opened 2021-05-21 13:44 UTC by sebastienmusso

Add the capability to change recordset project ID for openstack_dns_recordset_v2

2021-05-22 12:03 UTC, ozerovandrei commented on openstack/dns_zone_v2.go
> +		log.Printf("[DEBUG] request headers set: %#v", headers)
Why this message is changed?

2021-05-22 12:05 UTC, ozerovandrei requested changes

2021-05-22 12:05 UTC, ozerovandrei commented on openstack/resource_openstack_dns_recordset_v2.go
> +
I don't think that separating `err` from `err != nil` is a good style.

2021-05-22 12:05 UTC, ozerovandrei commented on openstack/resource_openstack_dns_recordset_v2_test.go
> +	//"log"
This should be removed.

2021-05-22 12:05 UTC, ozerovandrei commented on openstack/resource_openstack_dns_recordset_v2_test.go
> +		//log.Printf("[DEBUG] 2 ----------------------- %#v", rs.Primary.Attributes["project_id"])
This should be removed.

2021-05-23 08:54 UTC, sebastienmusso commented on openstack/dns_zone_v2.go
> +		log.Printf("[DEBUG] request headers set: %#v", headers)
Besause same function is used by resource of type recordset, in order to not being specific to dns zone resources only

2021-05-23 09:00 UTC, sebastienmusso commented on openstack/resource_openstack_dns_recordset_v2_test.go
> +	//"log"
Fixed

2021-05-23 09:00 UTC, sebastienmusso commented on openstack/resource_openstack_dns_recordset_v2_test.go
> +		//log.Printf("[DEBUG] 2 ----------------------- %#v", rs.Primary.Attributes["project_id"])
Fixed

2021-05-23 09:01 UTC, sebastienmusso commented on openstack/resource_openstack_dns_recordset_v2.go
> +
You mean have same error message for both dns client configuration ans dns header ?

2021-05-23 15:48 UTC, ozerovandrei commented on openstack/resource_openstack_dns_recordset_v2.go
> +
No I meant the empty line. Same error message is fine :)

2021-05-23 16:21 UTC, sebastienmusso commented on openstack/resource_openstack_dns_recordset_v2.go
> +
Yes right done in the last commit

2021-05-23 16:51 UTC, ozerovandrei commented
Looks fine but I want to run `recheck designate` in this PR after https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1253 is resolved.

2021-07-05 16:55 UTC, nikParasyr commented
recheck

2021-07-05 17:07 UTC, nikParasyr commented
recheck designate

2021-07-05 19:56 UTC, sebastienmusso commented
> Build succeeded.
> 
> - [terraform-provider-openstack-unittest-foo ](https://logs.openlabtesting.org/logs/54/1254/651571abb8abeadf19a67af12d57227ec52cb0e2/check/terraform-provider-openstack-unittest-foo/b82bd9b/) : SUCCESS in 4m 19s
> - [terraform-provider-openstack-acceptance-test-foo ](https://logs.openlabtesting.org/logs/54/1254/651571abb8abeadf19a67af12d57227ec52cb0e2/check/terraform-provider-openstack-acceptance-test-foo/f2f848c/) : SUCCESS in 2h 15m 18s
> - [terraform-provider-openstack-acceptance-test-admin-foo ](https://logs.openlabtesting.org/logs/54/1254/651571abb8abeadf19a67af12d57227ec52cb0e2/check/terraform-provider-openstack-acceptance-test-admin-foo/e931b38/) : SUCCESS in 49m 45s
> 

Yes !!! Here we go

2021-07-06 06:08 UTC, nikParasyr commented
> Build failed.
> 
>     * [terraform-provider-openstack-acceptance-test-designate-foo ](https://logs.openlabtesting.org/logs/54/1254/651571abb8abeadf19a67af12d57227ec52cb0e2/recheck-designate/terraform-provider-openstack-acceptance-test-designate-foo/770c676/) : FAILURE in 39m 38s

@sebastienmusso This test-set is more important and it is failing. I haven't had the time to go through the logs etc but by searching for `FAIL` you should be able to see which tests fail.

2021-07-06 09:48 UTC, sebastienmusso commented
Hi,

it seems to miss some permission within openstack api:

```
POST http://192.168.0.21/identity/v3/projects], error message: {"error":{"code":403,"message":"You are not authorized to perform the requested action: identity:create_project.","title":"Forbidden"}}
```

In the test, I create an openstack project and a dns record inside it.
The test user does't seems to have sufficient permissions.

2021-07-07 17:07 UTC, nikParasyr commented
@sebastienmusso sorry for the late reply. After having a look, it is a bit harder to properly fix the test scenario. I'll give some context:

In general a job(and all tests in that job) run as a single openstack user, who is either a `member` (the typical openstack `user` role) or an `admin`. Some tests need to be run on a job that is admin and some on the one that is a member. Unfortunately currently we don't have a more dynamic way of changing the permissions of a user within a job.  For that reason our typical check has 2 jobs(excluding the unit tests), one for the admin tests and one for the user tests.

The designate job runs as a `member`, which means you don't have permissions to create a project (which is required for your test case). Some of the options:
1. You don't create a project but you get the current project_id that the user belongs to (basically the env var OS_PROJECT_ID, a helper function could do that and then you pass it as a var in your`testAccDNSV2RecordSetDifferentProject`) and use that (i'm not 100% sure this will be enough).
2. We create a new job for designate where you have admin credentials therefore you can create a project. In this case and based on your docs(`The ID of the project DNS zone is created
  for, sets X-Auth-Sudo-Tenant-ID header (requires an assigned 
  user role in target project)`) you should also add a role association to that project which is currently missing.
  
  
My opinion is that if case 1 works then that's better cause we don't add yet another job. Otherwise for the option 2 i can create an MR with the new admin job, unfortunately it might take some time for our test infrastructure to be updated due to how its being managed. After that you can rebase and update your test accordingly. I'd like @ozerovandrei opinion on this. It's quite some work to cover one test case unfortunately.

Hopefully this explains some things to you.

2021-07-08 06:20 UTC, ozerovandrei commented
It seems that the first way is easier if it worked.

2021-07-09 15:22 UTC, sebastienmusso commented
I simplify test scenario. No more project are created and dns entry is created with "project_id" argument

2021-07-09 15:44 UTC, nikParasyr commented
recheck designate

2021-07-12 08:50 UTC, sebastienmusso commented
recheck designate

2021-07-12 12:04 UTC, sebastienmusso commented
Here we go !

2021-07-13 18:29 UTC, sebastienmusso commented
recheck designate

2021-07-15 16:59 UTC, ozerovandrei approved these changes
LGTM

Thank you @sebastienmusso

2021-07-15 16:59 UTC, merged