image: set forcenew=false on min_disk_gb, min_ram_mb, protected
terraform-provider-openstack/terraform-provider-openstack pull request #1299
Opened 2021-10-13 18:19 UTC by rossengeorgiev

On images allow setting these properties in-place: `min_disk_gb`, `min_ram_mb`, `protected`

Closes #1287

⚠ I'm not sure whether this is all I need to do to fix this. There maybe code and tests that need to be modified

2021-12-04 11:07 UTC, ozerovandrei requested changes

2021-12-04 11:07 UTC, ozerovandrei commented on openstack/resource_openstack_images_image_v2.go
> +				ForceNew:     false,
We usually don't add `ForceNew` field if it doesn't need to be set to `true` since it's `false` by default.
Could you just remove those lines?

2021-12-08 15:31 UTC, rossengeorgiev commented on openstack/resource_openstack_images_image_v2.go
> +				ForceNew:     false,
Done. Does any code need to be modified beyond that to address the issue?

2021-12-09 16:27 UTC, ozerovandrei approved these changes
LGTM, thank you @rossengeorgiev

2021-12-09 16:28 UTC, merged