r/d/networking_network_v2: add providerext attributes
terraform-provider-openstack/terraform-provider-openstack pull request #1309
Opened 2021-11-04 15:15 UTC by yanndegat

* `physical_network` - The physical network where this network is implemented.
* `segmentation_id` - An isolated segment on the physical network.
* `network_type` - The type of physical network.

2021-11-04 15:54 UTC, TomEros approved these changes
Looks cool

2021-11-05 08:02 UTC, yanndegat commented
hi @jtopjian 

i have an issue with the acctests on this PRs.

i'm not sure the failing tests are due to my PRs.
they are related to the `openstack_networking_trunk_v2` resource and according tests. but my PR only adds attributes to a network resource.

here's the error raised by the test on my PR:
 Error: Error creating openstack_networking_trunk_v2: Resource not found with openstack_networking_trunk_v2.trunk_1,

& when i locally run the same test, on the "main" branch, i have the same error.
do you have any clue on this ?

thanks a lot

2021-11-05 18:18 UTC, jtopjian commented
@yanndegat "Resource not found" might be that the trunk extension is not enabled - maybe removing it or not enabling it was a recent change in the upstream OpenStack code?

2021-11-08 08:16 UTC, yanndegat commented
hi @jtopjian 

thanks for your feedback. Is there anything i should do ?

2021-11-10 10:20 UTC, yanndegat commented
hi @ozerovandrei

i have CI issues on this PR, do you know what i should do to get it fixed ?

thanks a lot

2021-11-30 13:58 UTC, ozerovandrei commented on openstack/data_source_openstack_networking_network_v2.go
> +	segments := make([]map[string]interface{}, len(network.Segments))
Shouldn't it be
```go
segments := make([]map[string]interface{}, 0, len(network.Segments))
```

Otherwise we will get segments slice with some empty elements at the beginning: https://go.dev/play/p/HAEUmMzyJ56

2021-11-30 14:00 UTC, ozerovandrei commented
Trunk tests will be disabled https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1323

2021-11-30 14:07 UTC, yanndegat commented on openstack/data_source_openstack_networking_network_v2.go
> +	segments := make([]map[string]interface{}, len(network.Segments))
updated. thanks

2021-12-01 18:47 UTC, ozerovandrei requested changes

2021-12-01 18:47 UTC, ozerovandrei commented on website/docs/d/networking_network_v2.html.markdown
> +* `physical_network` - The physical network where this network is implemented.
I guess that datasource docs should also have `segments` in attributes.

2021-12-02 09:09 UTC, yanndegat commented on website/docs/d/networking_network_v2.html.markdown
> +* `physical_network` - The physical network where this network is implemented.
done. thanks for pointing this one

2021-12-04 10:39 UTC, ozerovandrei approved these changes
LGTM

2021-12-04 10:39 UTC, merged