Added monitor_port and monitor_address to lb_members_v2
terraform-provider-openstack/terraform-provider-openstack pull request #1363
Opened 2022-04-04 15:30 UTC by tdressen

Added the missing arguments for monitor_address and monitor_port to the lb_members_v2 resource.

This should fix my issue #1360

2022-04-06 10:17 UTC, flashjmp commented
There seems to be an issue in the devstack-gate project as there is a dependecy chain (zuul -> devstack-gate -> script -> ara -> markup -> jinja2) that is broken somewhere near the end.
I created an issue with the devstack-gate project here: https://storyboard.openstack.org/#!/story/2009973

2022-04-26 12:22 UTC, flashjmp commented
recheck lbaas

2022-05-15 12:01 UTC, ozerovandrei commented
Needs to be tested after fixing https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1366

2022-07-14 13:16 UTC, flashjmp commented
> @flashjmp can you rebase? There is an octavia job atm for testing changes

@nikParasyr: Done...

2022-07-15 11:52 UTC, flashjmp commented
Hi there, 
I fixed the slight hickup regarding linting, cloud somebody please trigger the workflows? (@nikParasyr / @ozerovandrei ) ?
Thanks !

2022-07-18 06:25 UTC, flashjmp commented
@nikParasyr or @ozerovandrei , could your please review and merge? Thx !

2022-07-21 06:59 UTC, nikParasyr requested changes
Hello. Could you fix the indentations?

Moreover the tests are skipped due to some unnecessary check. I'm removing it on #1412. So if you could wait for it to be merged and then rebase that would be great.

Other than that it looks good. Thank you

2022-07-21 06:59 UTC, nikParasyr commented on openstack/resource_openstack_lb_members_v2_test.go
> +		monitor_address = "192.168.199.110"
indentation

2022-07-21 06:59 UTC, nikParasyr commented on openstack/resource_openstack_lb_members_v2_test.go
> +		monitor_address = "192.168.199.111"
same

2022-07-21 06:59 UTC, nikParasyr commented on openstack/resource_openstack_lb_members_v2_test.go
> +		monitor_address = "192.168.199.10"
same

2022-07-21 06:59 UTC, nikParasyr commented on openstack/resource_openstack_lb_members_v2_test.go
> +		monitor_address = "192.168.199.11"
same

2022-07-22 08:26 UTC, nikParasyr commented on openstack/resource_openstack_lb_members_v2_test.go
> +<<<<<<< HEAD
same

2022-07-22 16:53 UTC, nikParasyr requested changes

2022-07-22 16:53 UTC, nikParasyr commented on openstack/lb_v2_shared.go
> +				MonitorPort:    &monitorPort,
MonitorPort and MonitorAddress should be set only when specified from the user as done below with `backup`. Otherwise if they are not specified they get value `0` which is wrong

2022-07-22 18:12 UTC, flashjmp commented on openstack/lb_v2_shared.go
> +				MonitorPort:    &monitorPort,
Thx for the head's up, I'm not the world's biggest Go programmer (obviously) and didn't interpret the if clause properly... :-(

I tried to orient myself on the other parameters.... (in terms of optional/required) which brings up the following question:  As only the address and protocol_port are actually required (https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/lb_members_v2), don't then all of those parameters should be checked for existence?

2022-07-25 07:48 UTC, nikParasyr commented on openstack/lb_v2_shared.go
> +				MonitorPort:    &monitorPort,
> don't then all of those parameters should be checked for existence?

In theory yes, in practice it is a case by case thing based on the attribute and how the openstack api handles it. For example `backup` could always be set and not only conditionally since if its not defined by the user it will get `false` value, which is the default that the api uses anywayz. So the behavior would not change. The reason why we still do it conditionally is because `backup` was added on octavia 2.1 and we still want the resource to work for users with 2.0. So if we dint have the conditional it would get value `false` and an octavia 2.0 would complain that attribute `backup` is not recognized.

For monitorPort it not defined by the users it gets value '0' which the api doesnt accept.

And that is how you can basically "check"/"understand"/"think" whether an attribute needs to be set conditionally or not.

2022-07-25 08:04 UTC, flashjmp commented on openstack/lb_v2_shared.go
> +				MonitorPort:    &monitorPort,
@nikParasyr: Could you please trigger the workflow and also have a quick look at my question above? Thx

2022-07-26 06:25 UTC, nikParasyr commented on openstack/lb_v2_shared.go
> +				MonitorPort:    &monitorPort,
```
2022-07-25T10:12:30.7469548Z 2022/07/25 10:12:30 [DEBUG] OpenStack Response Body: {
2022-07-25T10:12:30.7469793Z   "debuginfo": null,
2022-07-25T10:12:30.7470005Z   "faultcode": "Client",
2022-07-25T10:12:30.7470525Z   "faultstring": "Invalid input for field/attribute monitor_port. Value: '0'. Value should be greater or equal to 1"
2022-07-25T10:12:30.7470810Z }
2022-07-25T10:12:30.7557960Z 2022-07-25T10:12:30.754Z [WARN]  sdk.helper_resource: Error running Terraform CLI command: test_name=TestAccLBV2Members_basic test_step_number=3 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest2968115663
2022-07-25T10:12:30.7561252Z   error=
2022-07-25T10:12:30.7561653Z   | exit status 1
2022-07-25T10:12:30.7562835Z   | 
2022-07-25T10:12:30.7564806Z   | Error: Unable to update member 7fe6961d-011a-44d2-852a-18a9707d4686: Bad request with: [PUT http://10.1.1.228/load-balancer/v2.0/lbaas/pools/7fe6961d-011a-44d2-852a-18a9707d4686/members], error message: {"faultcode": "Client", "faultstring": "Invalid input for field/attribute monitor_port. Value: '0'. Value should be greater or equal to 1", "debuginfo": null}
2022-07-25T10:12:30.7566058Z   | 
2022-07-25T10:12:30.7567324Z   |   with openstack_lb_members_v2.members_1,
2022-07-25T10:12:30.7568313Z   |   on terraform_plugin_test.tf line 33, in resource "openstack_lb_members_v2" "members_1":
2022-07-25T10:12:30.7569683Z   |   33: resource "openstack_lb_members_v2" "members_1" {
2022-07-25T10:12:30.7570469Z   | 
2022-07-25T10:12:30.7570946Z   
2022-07-25T10:12:30.7573075Z 2022-07-25T10:12:30.754Z [DEBUG] sdk.helper_resource: Stopping providers: test_name=TestAccLBV2Members_basic test_step_number=3 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest2968115663
2022-07-25T10:12:30.7575014Z 2022-07-25T10:12:30.755Z [ERROR] sdk.helper_resource: Unexpected error: test_name=TestAccLBV2Members_basic test_step_number=3 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest2968115663
2022-07-25T10:12:30.7576064Z   error=
2022-07-25T10:12:30.7576641Z   | Error running apply: exit status 1
2022-07-25T10:12:30.7577500Z   | 
2022-07-25T10:12:30.7579105Z   | Error: Unable to update member 7fe6961d-011a-44d2-852a-18a9707d4686: Bad request with: [PUT http://10.1.1.228/load-balancer/v2.0/lbaas/pools/7fe6961d-011a-44d2-852a-18a9707d4686/members], error message: {"faultcode": "Client", "faultstring": "Invalid input for field/attribute monitor_port. Value: '0'. Value should be greater or equal to 1", "debuginfo": null}
2022-07-25T10:12:30.7580286Z   | 
2022-07-25T10:12:30.7581526Z   |   with openstack_lb_members_v2.members_1,
2022-07-25T10:12:30.7582508Z   |   on terraform_plugin_test.tf line 33, in resource "openstack_lb_members_v2" "members_1":
2022-07-25T10:12:30.7583797Z   |   33: resource "openstack_lb_members_v2" "members_1" {
2022-07-25T10:12:30.7584580Z   | 
2022-07-25T10:12:30.7585247Z   
2022-07-25T10:12:30.7586025Z     resource_openstack_lb_members_v2_test.go:36: Step 3/4 error: Error running apply: exit status 1
2022-07-25T10:12:30.7586846Z         
2022-07-25T10:12:30.7588802Z         Error: Unable to update member 7fe6961d-011a-44d2-852a-18a9707d4686: Bad request with: [PUT http://10.1.1.228/load-balancer/v2.0/lbaas/pools/7fe6961d-011a-44d2-852a-18a9707d4686/members], error message: {"faultcode": "Client", "faultstring": "Invalid input for field/attribute monitor_port. Value: '0'. Value should be greater or equal to 1", "debuginfo": null}
2022-07-25T10:12:30.7590258Z         
2022-07-25T10:12:30.7590608Z           with openstack_lb_members_v2.members_1,
2022-07-25T10:12:30.7591176Z           on terraform_plugin_test.tf line 33, in resource "openstack_lb_members_v2" "members_1":
2022-07-25T10:12:30.7591658Z           33: resource "openstack_lb_members_v2" "members_1" {
2022-07-25T10:12:30.7592045Z         
2022-07-25T10:12:30.7592888Z 2022-07-25T10:12:30.755Z [DEBUG] sdk.helper_resource: Creating sdkv2 provider instance: test_name=TestAccLBV2Members_basic test_step_number=3 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest2968115663 tf_provider_addr=registry.terraform.io/hashicorp/openstack
2022-07-25T10:12:30.7594014Z 2022-07-25T10:12:30.755Z [DEBUG] sdk.helper_resource: Created sdkv2 provider instance: test_name=TestAccLBV2Members_basic test_step_number=3 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest2968115663 tf_provider_addr=registry.terraform.io/hashicorp/openstack
2022-07-25T10:12:30.7595247Z 2022-07-25T10:12:30.755Z [DEBUG] sdk.helper_resource: Starting sdkv2 provider instance server: test_name=TestAccLBV2Members_basic test_step_number=3 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest2968115663 tf_provider_addr=registry.terraform.io/hashicorp/openstack
2022-07-25T10:12:30.7596363Z 2022-07-25T10:12:30.755Z [DEBUG] sdk.helper_resource: Started sdkv2 provider instance server: test_name=TestAccLBV2Members_basic test_step_number=3 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest2968115663 tf_provider_addr=registry.terraform.io/hashicorp/openstack
2022-07-25T10:12:30.8113538Z 2022-07-25T10:12:30.810Z [DEBUG] sdk.helper_resource: Stopping providers: test_name=TestAccLBV2Members_basic test_step_number=3 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest2968115663
```

Tests are still failing. I was expecting conditionally setting to solve this one. 
@ozerovandrei could you have a look? I think im missing something very basic here

2022-07-26 06:49 UTC, flashjmp commented on openstack/lb_v2_shared.go
> +				MonitorPort:    &monitorPort,
Hi @nikParasyr and @ozerovandrei ,

I activated debugging capabilities for the provider and looked into the data structures last night. It looks like the gopher SDK actually always returns "monitor_port" and "monitor_address" which is why only testing for existence is not sufficient.
I am currently testing the following locally which does seem reasonable to me:

`// Only set monitor_port and monitor_address when explicitly specified, as they are optional arguments
			if val, ok := rawMap["monitor_port"]; ok {
				monitorPort := val.(int)
				if monitorPort > 0 {
					member.MonitorPort = &monitorPort
				}
			}

			if val, ok := rawMap["monitor_address"]; ok {
				monitorAddress := val.(string)
				if monitorAddress != "" {
					member.MonitorAddress = &monitorAddress
				}
			}`

2022-07-26 08:19 UTC, flashjmp commented on openstack/lb_v2_shared.go
> +				MonitorPort:    &monitorPort,
@nikParasyr , could you please trigger the WF (hopefully for this last time on this PR ;-) )

2022-07-27 07:57 UTC, nikParasyr commented on main.go
> +	// added debugMode to enable debugging for provider per https://www.terraform.io/plugin/sdkv2/debugging
@ozerovandrei can you have a look into this? seems right to me, just want to make sure there are no side-effects im not aware off

2022-07-27 07:58 UTC, nikParasyr approved these changes
@flashjmp This is good. I only have a minor thing i want to doublecheck. Thank you for all the work and patience. Hopefully next ones will fly faster :)

2022-07-29 06:03 UTC, ozerovandrei commented on main.go
> +	// added debugMode to enable debugging for provider per https://www.terraform.io/plugin/sdkv2/debugging
Looks fine by me.

2022-07-29 06:03 UTC, ozerovandrei approved these changes

2022-07-29 07:03 UTC, flashjmp commented
@nikParasyr could you merge then pls?

2022-07-29 07:27 UTC, merged