Add servergroup policy and rules field support
terraform-provider-openstack/terraform-provider-openstack pull request #1382
Opened 2022-05-31 12:40 UTC by Tjev

Should resolve #1143. 

Addition of `policy` and `rules` fields, which replace the `policies` field since API microversion 2.64. Support for the fields has already been added to Gophercloud.

2022-07-21 08:44 UTC, nikParasyr commented
@Tjev Sorry for the very long delay. CI has been fixed and I rebased to run the tests etc. could you check as the servergroup tests are failing

2022-07-21 12:39 UTC, Tjev commented
Hello @nikParasyr, I fixed the linter errors and amended the changes. Could I please ask for a re-run of the CI?

2022-09-26 15:27 UTC, nikParasyr requested changes
Hi @Tjev , I actually had some time now :)

I've added some comments in the review.

Moreover, for the tests failing I see in the logs:
```
2022-09-22T10:31:31.8755532Z   |   # openstack_compute_servergroup_v2.sg_1 must be replaced
2022-09-22T10:31:31.8755973Z   | -/+ resource "openstack_compute_servergroup_v2" "sg_1" {
2022-09-22T10:31:31.8756461Z   |       ~ id       = "89ac55b0-baac-46e5-b2be-306dc0851d33" -> (known after apply)
2022-09-22T10:31:31.8756913Z   |       ~ members  = [] -> (known after apply)
2022-09-22T10:31:31.8757160Z   |         name     = "sg_1"
2022-09-22T10:31:31.8757419Z   |       - policies = [
2022-09-22T10:31:31.8757693Z   |           - "affinity",
2022-09-22T10:31:31.8758004Z   |         ] -> null # forces replacement
2022-09-22T10:31:31.8758364Z   |       ~ region   = "RegionOne" -> (known after apply)
2022-09-22T10:31:31.8758664Z   |         # (1 unchanged attribute hidden)
2022-09-22T10:31:31.8758888Z   |     }
```
for multiple tests. This basically indicated that the Read function is not working properly.
From reading a bit the docs [here](https://docs.openstack.org/api-ref/compute/?expanded=show-server-group-details-detail#create-server-group) it looks like `policies` is available till 2.63 and then from 2.64 `policy` and `rules` are available. 
In the Read function you dont set Microversion which means that you could set policy/rules on the create, but will not read these proeprties as its using <=2.63 microversion and thus not set them.

So i would first try to read with 2.64 MicroVersion and if its successful set `policy` and `rules`, otherwise if i get an error i'd try to read without setting a Microversion and set `policies`. If i still get an error then just return the error.

I hope this makes sense.

2022-09-30 16:35 UTC, Tjev commented
Hello again @nikParasyr !
Thanks a lot for the help. I tried to reflect your feedback in the changes I made. Hopefully everything seems ok now (and the pipeline passes 😄).

2022-10-12 13:31 UTC, nikParasyr submitted a review, later dismissed
@Tjev Im not sure why the ci is not running. I tried to kick it but it doesnt. In any case. I've made a couple of comments. Hopefully when you push these changes the ci will work properly. Also
```
gofmt -s -w .
```
before comitting will save you from various linting issues

2022-10-12 13:31 UTC, nikParasyr commented on openstack/resource_openstack_compute_servergroup_v2.go
> +		if policy != "" {
This check is un-necessary as I mentioned, because the `conflictsWith` will already return an err message if a user defines `policies` and policy or rules.

2022-10-12 13:31 UTC, nikParasyr commented on openstack/resource_openstack_compute_servergroup_v2.go
> +		if rulesPresent {
same as above

2022-11-02 17:27 UTC, Tjev commented
Hello @nikParasyr, once again, I tried to include your feedback. Sorry for the formatting errors, I had some issues with my local go env (gofmt would not work, etc..) and I didn't have enough time on my hands to fix it properly. I was now able to format as instructed (`gofmt -s -w .`).

I left the singular check for presence of `policy` field in order to properly set the microversion used. Hopefully the changes look okay now.

2023-03-11 10:42 UTC, kayrus commented
@Tjev I rebased your PR to trigger tests.

2023-03-13 21:37 UTC, kayrus approved these changes
LGTM

2023-03-14 08:19 UTC, nikParasyr approved these changes
LGTM

2023-03-14 08:20 UTC, merged

2023-03-14 10:15 UTC, Tjev commented
Thank you @nikParasyr & @kayrus !