Added monitor-address and monitor-port to openstack_lb_member_v2
terraform-provider-openstack/terraform-provider-openstack pull request #1390
Opened 2022-07-07 14:47 UTC by luigizhou

Added missing arugment for monitor_address and monitor_port to the lb_member_v2 resource.
Replaced the pools library with the one from octavia loadbalancer instead of neutron.

Doesn't seem to break functionality from my test, so not sure why neutron pools were used instead...

2022-07-08 07:36 UTC, flashjmp commented
Hi @luigizhou ,
I added these parameters to the lb_members_v2 (which is based on octavia, see here: #1363 )
From my understanding the lb_member_v2 was intentionally kept as a neutron "legacy" version of this?

2022-07-08 07:58 UTC, flashjmp commented
I am pretty much done from my end, but there is obviously a review required and the whole project seems to be a little "stale" at the moment. The key issue is that the testing pipeline (#1366) is currently broken... :-(

2022-07-10 11:53 UTC, luigizhou commented
@flashjmp I've taken some time to look at the lb_members_v2 resource which is based on octavia as you mentioned.
One thing I noticed is that, compared to member_v2, there is now only a need for a single resource to manage all members of a pool, which looks less flexible and also more disruptive in cases you want to migrate from the old member_v2 to the new members_v2 (defining a members_v2 removes all members of a pool)

Don't you think it would make sense to upgrade the member_v2 resource instead to support octavia api?
Or alternatively defining a new resource that retain the same behaviour as member_v2, but uses octavia api underneath? Something like a 'lb_octavia_member_v2' ? 

I'm happy to work out another PR for it

2022-07-12 22:45 UTC, luigizhou commented
@ozerovandrei what do you think?

2022-07-16 13:59 UTC, luigizhou commented
Hey @nikParasyr , I should've been able to add support for octavia LB without breaking LBaaS compatibility

2022-07-19 15:02 UTC, luigizhou commented
Fixed linting @nikParasyr !

2022-07-20 14:22 UTC, nikParasyr requested changes
Hello.

Thank you for your MR. It looks good but there are a couple things missing:
- please update docs of the resource found [here](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/website/docs/r/lb_member_v2.html.markdown) with the new attributes of the resource
- please update the acceptance tests of the resource found [here](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_lb_member_v2_test.go) to test the new attributes as well.

2022-07-26 09:31 UTC, luigizhou commented
@nikParasyr I've updated the docs, but I'm not entirely sure what version exactly Octavia started supporting monitor_port and address.

I've laso updated the acceptance tests, let me know if those looks good 👍

2022-07-26 12:09 UTC, nikParasyr requested changes
Hey, tests are failing and i have some nit fixes as well.

2022-07-26 12:09 UTC, nikParasyr commented on openstack/resource_openstack_lb_member_v2_test.go
> +					resource.TestCheckResourceAttr("openstack_lb_member_v2.member_1", "monitor_port", "443"),
`openstack_lb_member_v2.member_1` => needs to be openstack_lb_member_v2.member_2 if im correct.

Test failing with:
```
2022-07-26T11:23:23.6415792Z 2022-07-26T11:23:23.641Z [ERROR] sdk.helper_resource: Unexpected error: test_name=TestAccLBV2Member_monitor test_step_number=2 test_terraform_path=/usr/local/bin/terraform test_working_directory=/tmp/plugintest4229929319 error="Check failed: Check 2/2 error: openstack_lb_member_v2.member_1: Attribute 'monitor_port' expected \"443\", got \"8080\""
2022-07-26T11:23:23.6417153Z     resource_openstack_lb_member_v2_test.go:103: Step 2/2 error: Check failed: Check 2/2 error: openstack_lb_member_v2.member_1: Attribute 'monitor_port' expected "443", got "8080"
```

2022-07-26 12:09 UTC, nikParasyr commented on openstack/resource_openstack_lb_member_v2_test.go
> +					resource.TestCheckResourceAttr("openstack_lb_member_v2.member_1", "monitor_port", "8080"),
openstack_lb_member_v2.member_1 => needs to be openstack_lb_member_v2.member_2 if im correct.

2022-07-26 12:09 UTC, nikParasyr commented on openstack/resource_openstack_lb_member_v2_test.go
> +				Config: TestAccLbV2MemberConfigBasic,
`nit change`
- since you are adding a new test scenario all together can you add a specific config for this scenario as well instead of using the existing `TestAccLbV2MemberConfigBasic`?

2022-07-26 12:09 UTC, nikParasyr commented on openstack/resource_openstack_lb_member_v2_test.go
> +func TestAccLBV2Member_monitor(t *testing.T) {
`nit change`:
could you also put this before `func testAccCheckLBV2MemberDestroy`? we typically want to have all test scenarios one after the other. Thanks

2022-07-26 17:07 UTC, luigizhou commented on openstack/resource_openstack_lb_member_v2_test.go
> +					resource.TestCheckResourceAttr("openstack_lb_member_v2.member_1", "monitor_port", "443"),
this should be fixed

2022-07-26 17:07 UTC, luigizhou commented on openstack/resource_openstack_lb_member_v2_test.go
> +					resource.TestCheckResourceAttr("openstack_lb_member_v2.member_1", "monitor_port", "8080"),
This is also fixed now

2022-07-26 17:07 UTC, luigizhou commented on openstack/resource_openstack_lb_member_v2_test.go
> +				Config: TestAccLbV2MemberConfigBasic,
Added a specific config and undone the changes in the basic one

2022-07-26 17:08 UTC, luigizhou commented on openstack/resource_openstack_lb_member_v2_test.go
> +func TestAccLBV2Member_monitor(t *testing.T) {
Moved the test scenario before the memberdestroy function 👍

2022-07-26 17:08 UTC, luigizhou commented
@nikParasyr when you have time can you review again?

2022-07-27 12:42 UTC, nikParasyr requested changes

2022-07-27 12:42 UTC, nikParasyr commented on openstack/resource_openstack_lb_member_v2_test.go
> +  monitor_address = "192.168.199.111
`"` missing at the end. Tests are failing due to this.

2022-07-27 19:55 UTC, luigizhou commented on openstack/resource_openstack_lb_member_v2_test.go
> +  monitor_address = "192.168.199.111
Thanks, I sorted that out 👍

2022-07-28 08:23 UTC, nikParasyr approved these changes

2022-07-29 07:28 UTC, merged