Implement rule for openstack_networking_secgroup_v2
terraform-provider-openstack/terraform-provider-openstack pull request #1458
Opened 2022-11-29 16:13 UTC by baurmatt

This PR implements a new `rule` attribute for the `openstack_networking_secgroup_v2` resource. Most of this was copied from the deprecated `openstack_compute_secgroup_v2` resource.

2022-12-04 10:29 UTC, nikParasyr requested changes
Couple of indentation changes please.

Other than that, it is ok from my side. Although i have to mention that i'm not a big fan of managing multiple openstack resources from a single terraform resource. Makes the code more complicated than it should be and less maintainable. It also goes against terraform best practises. That being said i will not block it, but i will leave the final call to @ozerovandrei. This PR should also address the issue mentioned in #1456 as the delete will wipe the security group which automatically will delete all the rules.

2022-12-04 10:29 UTC, nikParasyr commented on openstack/resource_openstack_networking_secgroup_v2_test.go
> +	  ethertype        = "IPv4"
fix indentation plz

2022-12-04 10:29 UTC, nikParasyr commented on openstack/resource_openstack_networking_secgroup_v2_test.go
> +	  ethertype        = "IPv4"
indentation here as well

2022-12-05 09:51 UTC, baurmatt commented
@nikParasyr Thanks for the review! :) I've fix the indention. About https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1456, that's correctly implemented for `openstack_networking_secgroup_v2` - it will just deletes the full security group, leaving the rules to OpenStack.

2022-12-05 12:05 UTC, baurmatt commented
Errr, I can't explain the CI failures and are unable to locate the actual error in the CI logs. I don't think it's related, as I've only changed the indention of some Terraform code -> https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1458/commits/c44799e5cabd62cf1e5d850470bb51a72f224bd1

2022-12-05 12:20 UTC, nikParasyr approved these changes

2022-12-08 15:03 UTC, ozerovandrei requested changes
> Although i have to mention that i'm not a big fan of managing multiple openstack resources from a single terraform resource. Makes the code more complicated than it should be and less maintainable. It also goes against terraform best practises.

@baurmatt Could you please provide more context about why we need to implement security group rules inside `openstack_networking_secgroup_v2` resource? I have the same concerns as @nikParasyr here.
 
And how it differs from the existing [resource_openstack_networking_secgroup_rule_v2.go](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_networking_secgroup_rule_v2.go)?

2022-12-09 16:22 UTC, baurmatt commented
@ozerovandrei I should have probably done this when creating this PR, sorry! I've updated the description with an explanation of the motivation behind this MR. Hope that helps! :)

2022-12-11 21:14 UTC, nikParasyr commented
@baurmatt thanks for the explanation. I’ve had the same issue and the way I resolved it is to have a list as the input of the module and then with the use of locals I build a map. The key of each item is the merge of ‘direction-protocol-min_port-max_port-…’ which should be unique. This allows me to use for_each and the benefits of it instead of count, while users don’t have to bother about passing/giving keys. Although it has some shortcomings as the generation of the map is a bit hard to understand.

2022-12-12 11:23 UTC, baurmatt commented
@nikParasyr You're right! This worked out pretty easy!

```terraform
locals {
  _rules_keys = [for rule in var.rules : "${coalesce(rule.direction, "x")}-${coalesce(rule.ethertype, "x")}-${coalesce(rule.description, "x")}-${coalesce(rule.protocol, "x")}-${coalesce(rule.port_range_min, "x")}-${coalesce(rule.port_range_max, "x")}-${coalesce(rule.remote_ip_prefix, "x")}-${coalesce(rule.remote_group_id, "x")}"]
  _rules      = { for rule in var.rules : local._rules_keys[index(var.rules, rule)] => rule }
}

resource "openstack_networking_secgroup_v2" "secgroup" {
  name                 = var.name
  description          = var.description
  delete_default_rules = true
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_rule" {
  for_each          = local._rules
  security_group_id = openstack_networking_secgroup_v2.secgroup.id
  direction         = each.value.direction
  ethertype         = each.value.ethertype
  description       = each.value.description
  protocol          = each.value.protocol
  port_range_min    = each.value.port_range_min
  port_range_max    = try(coalesce(each.value.port_range_max, each.value.port_range_min), null)
  remote_ip_prefix  = each.value.remote_ip_prefix
  tenant_id         = each.value.tenant_id
  remote_group_id   = each.value.remote_group_id == "this" ? openstack_networking_secgroup_v2.secgroup.id : each.value.remote_group_id
}
```

I remember that I've tried this before, but ended up with so much validation code that it was insane to maintain. This seems to have gotten way better with the latest updates of our module to list(object), optional attributes and validation!

Would there be any interest to build community driven modules where we can share those best practices? Can't really find good ones on the registry.

2022-12-13 10:36 UTC, nikParasyr commented
Good to hear that it works for you. Recent tf features have made this much easier than it used to be.

> Would there be any interest to build community driven modules where we can share those best practices? 

Not sure if there is interest for modules and maintaining them. Maybe we could update `examples/` with a set of more realistic modules/deployments. We could also consider to enable `Discussions` which could be more for questions/best-practices etc. Not sure what @ozerovandrei thinks about it.

In regards with this MR, do you still need the functionality it includes? I'm still against it for the reasons mentioned above, and since you can achieve what you want easily with modules I don't think it's really needed.

2022-12-14 08:04 UTC, baurmatt commented
I'm fine closing this PR. Thanks for your help! :)

2022-12-16 12:39 UTC, baurmatt commented
I have to reopen this as I've found another usecase for the implementation of this PR.

The suggested solution (https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1458#issuecomment-1346311175) above doesn't work if keys derived from resource attributes e.g. reference to an floating IP resources.

```terraform
terraform {
  required_providers {
    openstack = {
      source = "terraform-provider-openstack/openstack"
    }
  }
}

resource "openstack_networking_floatingip_v2" "fip" {
  pool = "ext-net"
}

module "security-group" {
  source = "/Users/mbaur/Sources/terraform-modules/openstack-security_group"
  name   = "security-group"
  rules = [
    {
      "protocol"         = "tcp"
      "port_range_min"   = "9200"
      "remote_ip_prefix" = "${openstack_networking_floatingip_v2.fip.address}/32"
    },
  ]
}
```

(The openstack-security_group module contains, more or less, the code I've posted in https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1458#issuecomment-1346311175)

The leads to the following error:

```
module.security-group.openstack_networking_secgroup_v2.secgroup: Refreshing state... [id=9ff0720a-1388-4494-80a1-e08013a25831]
╷
│ Error: Invalid for_each argument
│
│   on .terraform/modules/security-group/main.tf line 13, in resource "openstack_networking_secgroup_rule_v2" "secgroup_rule":
│   13:   for_each          = local._rules
│     ├────────────────
│     │ local._rules will be known only after apply
│
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify
│ the instances of this resource.
│
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
```

This works just fine for the implementation I suggest in this PR.

2022-12-23 13:46 UTC, rossengeorgiev commented
One thing I found frustrating about `openstack_networking_secgroup_v2` is that you can't deal with configuration drift. If someone adds rules outside of terraform, then terraform remains oblivious to it. This creates the following problems:

* configuration dift is undetected
* rules added outside of terraform would prevent `openstack_networking_secgroup_v2` from being destroyed
* rules added outside of terraform would collide when the exact same rule is added via terraform

This PR could potentially solve that. Alternatively, we `openstack_networking_secgroup_v2` could be implemented to manage both the security group and rules, while `openstack_networking_secgroup_rule_v2` would be like `null_resource` or `terraform_data`. Then a list of rules would be pasted to a `rules` attribute `openstack_networking_secgroup_v2`, which would then perform all the necessary API calls to make it so.

2023-01-31 09:11 UTC, baurmatt commented
Hey @nikParasyr and @ozerovandrei, what do you think about merging/releasing this PR? :)

2023-01-31 13:36 UTC, nikParasyr commented
Hello @baurmatt. Tbh, I’m still against it. I understand the reasoning and the use-cases behind it but this is an anti-pattern and the provider is “thinly”maintained atm.

2024-07-18 17:02 UTC, closed without merging