Add decompression flag to openstack_images_image_v2 resource
terraform-provider-openstack/terraform-provider-openstack pull request #1482
Opened 2023-02-16 18:03 UTC by spnngl

Some image are compressed and only filling Content-Type header resulting if uploading a compressed image to openstack.

With this we automatically detects and uncompress images in this case.

Example:
```
$ curl -I "https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_openstack_image.img.bz2"
HTTP/2 200
server: nginx
date: Thu, 16 Feb 2023 15:54:03 GMT
content-type: application/x-bzip2
content-length: 371535602
etag: "rq4xkz657ape"
last-modified: Wed, 15 Feb 2023 18:48:35 GMT
accept-ranges: bytes
```

2023-02-16 19:28 UTC, kayrus requested changes
thanks for your PR. I left a couple of comments.

2023-02-16 19:28 UTC, kayrus commented on openstack/images_image_v2.go
> +			if decompress && !resp.Uncompressed {
checking for `resp.Uncompressed` doesn't make sense, since it is used only for `Content-Encoding`

2023-02-16 19:28 UTC, kayrus commented on openstack/images_image_v2.go
> +					reader = io.NopCloser(bz2_reader)
Let's follow the golang var name standards.
```suggestion
					bz2Reader := bzip2.NewReader(resp.Body)
					reader = io.NopCloser(bz2Reader)
```

2023-02-16 19:28 UTC, kayrus commented on openstack/images_image_v2.go
> +			}
you can avoid `else` by initially setting the reader to `resp.Body` on the 132 line:

```
reader := resp.Body
```

2023-02-16 19:28 UTC, kayrus commented on openstack/resource_openstack_images_image_v2.go
> +			"decompress": {
can you mention this flag in documentation?

2023-02-16 19:47 UTC, kayrus commented
In addition please update the `CHANGELOG.md`:

```
## 1.50.0 (Not released yet)

FEATURES

IMPROVEMENTS

* ...

```

2023-02-17 09:06 UTC, spnngl commented on openstack/images_image_v2.go
> +			if decompress && !resp.Uncompressed {
I wanted to check if we're not trying to decompress something already decompressed by golang stack or which was never compressed to begin with

2023-02-17 09:36 UTC, spnngl commented on openstack/resource_openstack_images_image_v2.go
> +			"decompress": {
done

2023-02-17 10:13 UTC, spnngl commented
Did the modifications in the last version

2023-02-17 10:32 UTC, kayrus reviewed
Thanks. LGTM. Please fix the comments. And I think it's ready to be merged.

2023-02-17 10:32 UTC, kayrus commented on CHANGELOG.md
> +## 1.50.0 (17 February, 2023)
```suggestion
## 1.50.0 (Not released yet)
```

2023-02-17 10:32 UTC, kayrus commented on website/docs/r/images_image_v2.html.markdown
> +    image before uploading it to Openstack. Decompression algorithm is chosen by
```suggestion
    image before uploading it to OpenStack. Decompression algorithm is chosen by
```

2023-02-17 10:40 UTC, spnngl commented on website/docs/r/images_image_v2.html.markdown
> +    image before uploading it to Openstack. Decompression algorithm is chosen by
done

2023-02-17 10:40 UTC, spnngl commented on CHANGELOG.md
> +## 1.50.0 (17 February, 2023)
done

2023-02-17 10:41 UTC, spnngl commented
Updated

2023-02-17 10:45 UTC, kayrus approved these changes

2023-02-20 10:14 UTC, kayrus commented
@spnngl can you fix golang linter issues?

2023-02-20 10:26 UTC, kayrus commented
It also looks like OpenStack test env doesn't support web-download anymore. Can you add an exception and skip these tests for a while?

2023-02-20 13:56 UTC, spnngl commented
Pushed a new version with lint fix + web_download tests deactivated

2023-02-28 09:10 UTC, maxime1907 commented
Any update? We really need this to be merged!

2023-02-28 09:31 UTC, kayrus commented
I re-triggered glance tests, once they pass, the PR can be merged.

2023-02-28 10:17 UTC, kayrus commented
can you add a `"decompress"` exception into the import tests? Tests fail because of
```
ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

(map[string]string) {
}


(map[string]string) (len=1) {
 (string) (len=10) "decompress": (string) (len=5) "false"
}
```

https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/bd2071b1a27dfbe07f08797c3acd7410ff0a61c4/openstack/import_openstack_images_image_v2_test.go#L29-L33

2023-02-28 10:41 UTC, spnngl commented
I added the decompress ignore + rebase on main

2023-02-28 13:16 UTC, kayrus commented on openstack/resource_openstack_images_image_v2.go
> +				ForceNew: false,
I think it makes sense to set `ForceNew` to `true`. Objections?

2023-02-28 15:00 UTC, spnngl commented on openstack/resource_openstack_images_image_v2.go
> +				ForceNew: false,
You're right, I will make the modifications

2023-02-28 15:07 UTC, spnngl commented on openstack/resource_openstack_images_image_v2.go
> +				ForceNew: false,
Pushed it

2023-02-28 15:31 UTC, nikParasyr commented
Since `changelog` is updated this will trigger all the ci jobs. 

I think recently opendev,org added some limits to pulling repos etc and as we also have our daily check failing with a timeout. I need to have a look to make sure that the timeout is due to limits and think of a way to bypass it.

2023-02-28 19:13 UTC, kayrus commented
@nikParasyr @ozerovandrei  I was not aware about the behavior when changelog is changed. I think we can skip failed `functional-images` test, it has some issues with the data source. other tests are fine.
I think we can merge this PR.

2023-03-01 06:20 UTC, nikParasyr commented
@kayrus the idea behind this behavior with changelog is that we update it only before a release (or after multiple MRs are changed) and the whole ci runs to make sure all services are ok. But it can be a bit annoying if changelog is updated on each MR (also often we have conflicts due to that).

From my side this can be merged as well. The failing ci jobs are not related to this change.

2023-03-01 06:21 UTC, nikParasyr approved these changes

2023-03-01 06:22 UTC, merged