[network v2]: Add support for network segments update and import
terraform-provider-openstack/terraform-provider-openstack pull request #1508
Opened 2023-03-05 12:54 UTC by kayrus

Fixes #1477

2023-03-10 08:14 UTC, nikParasyr requested changes
@kayrus Just some doc updates. Other than that LGTM

2023-03-10 08:14 UTC, nikParasyr commented on openstack/data_source_openstack_networking_network_v2.go
> +	d.Set("segments", flattenNetworkingNetworkSegmentsV2(network))
Can you update docs to mention that segments are exported as well?

2023-03-10 08:14 UTC, nikParasyr commented on openstack/resource_openstack_networking_network_v2.go
> -							ForceNew: true,
Based on [docs](https://docs.openstack.org/api-ref/network/v2/index.html?expanded=update-network-detail#networks), this can only be updated if network_type == vlan. Can you update docs to mention this?

2023-03-10 13:49 UTC, kayrus commented on openstack/resource_openstack_networking_network_v2.go
> -							ForceNew: true,
You'r not quire right. It depends on the ml2 plugin. I added this info.

2023-03-10 13:49 UTC, kayrus commented on openstack/data_source_openstack_networking_network_v2.go
> +	d.Set("segments", flattenNetworkingNetworkSegmentsV2(network))
done

2023-03-11 09:34 UTC, nikParasyr approved these changes

2023-03-11 09:35 UTC, merged