[FWaaS_V2]: Add FW Group V2 resource
terraform-provider-openstack/terraform-provider-openstack pull request #1588
Opened 2023-06-27 11:59 UTC by Koodt

Add resourceFWGroupV2 CRUD
Add resourceFWGroupV2 tests
Add resourceFWGroupV2 docs
Add import_openstack_fw_group_v2_test
Enable openstack_fw_group_v2 in provider.go

Close part of #115

2023-06-27 19:40 UTC, kayrus reviewed
Thanks for the PR. See my notes.

2023-06-27 19:40 UTC, kayrus commented on openstack/fw_group_v2.go
> +		return diag.Errorf("Error waiting for openstack_fw_group_v2 %s to become active: %s", d.Id(), err)
```suggestion
		return diag.Errorf("Error waiting for openstack_fw_group_v2 %s to become deleted: %s", d.Id(), err)
```

2023-06-27 19:40 UTC, kayrus commented on openstack/fw_group_v2.go
> +		err := groups.Get(networkingClient, id).ExtractIntoStructPtr(&group, "firewall_group")
Is there a reason to call the `ExtractIntoStructPtr`? In the `fwGroupV2DeleteFunc` you're just calling `Extract`.
Maybe it makes sense to combine `fwGroupV2RefreshFunc` and `fwGroupV2DeleteFunc` into the one `fwGroupV2RefreshFunc`?

2023-06-27 19:40 UTC, kayrus commented on openstack/resource_openstack_fw_group_v2.go
> +		TenantID:                d.Get("tenant_id").(string),
Does it make sense to add `ProjectID` here as well?

2023-06-27 19:40 UTC, kayrus commented on openstack/resource_openstack_fw_group_v2.go
> +		return diag.Errorf("Error waiting for openstack_fw_firewall_v2 %s to Delete:  %s", d.Id(), err)
```suggestion
		return diag.Errorf("Error waiting for openstack_fw_firewall_v2 %s to delete:  %s", d.Id(), err)
```

2023-06-27 19:40 UTC, kayrus commented on openstack/resource_openstack_fw_group_v2.go
> +			},
This is a computed attribute. Also please move it to the bottom.
```suggestion
			"status": {
				Type:     schema.TypeString,
				Computed: true,
			},
```

2023-06-27 19:40 UTC, kayrus commented on website/docs/r/fw_group_v2.html.markdown
> +    Changing this updates the `admin_state_up` of an existing firewall group.
this should be removed, since it's a computed attribute. Also please add a corresponding description in the attribute reference.

2023-06-27 19:40 UTC, kayrus commented on website/docs/r/fw_group_v2.html.markdown
> +* `project_id` - (Optional) The owner of the firewall group. Required if admin
Please give a description about the difference of `project_id` and `tenant_id`. Do you think it makes sense to add `ConflictsWith` in the schema definition?

2023-06-28 06:23 UTC, nikParasyr requested changes

2023-06-28 06:23 UTC, nikParasyr commented on website/docs/r/fw_group_v2.html.markdown
> +    "${openstack_fw_rule_v2.rule_1.id}",
Can you remove `${`, `}` from the examples as it is quite old syntax? with https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1585 all the examples were updated

2023-06-28 06:23 UTC, nikParasyr commented on website/docs/r/fw_group_v2.html.markdown
> +* `project_id` - (Optional) The owner of the firewall group. Required if admin
I also think `ConflictsWith` might be good.

2023-06-28 07:27 UTC, Koodt commented on openstack/fw_group_v2.go
> +		return diag.Errorf("Error waiting for openstack_fw_group_v2 %s to become active: %s", d.Id(), err)
We don't delete the group, but wait for its status after deleting a policy from it.

2023-06-28 09:18 UTC, Koodt commented on openstack/fw_group_v2.go
> +		err := groups.Get(networkingClient, id).ExtractIntoStructPtr(&group, "firewall_group")
Call the `ExtractIntoStructPtr` is needed to return the status dynamically.
I think returning nill error after `gophercloud.ErrDefault404` when we create or update firewall group would be a bad idea.
So, I decided to separate them

2023-06-28 09:55 UTC, Koodt commented on website/docs/r/fw_group_v2.html.markdown
> +* `project_id` - (Optional) The owner of the firewall group. Required if admin
Description - ok
Why tenant conflict with project? It's the same.
They will only conflict if there are different values. 
In this case, we need the `ConflictsWith`

2023-06-28 11:44 UTC, nikParasyr commented on website/docs/r/fw_group_v2.html.markdown
> +* `project_id` - (Optional) The owner of the firewall group. Required if admin
I think in its current form it can be a bit confusing for the user:
1. they might either define both with the same value, duplication for no reason
2. they might define them with a different value which will lead to an error

So `ConflictsWith` solves the above and then it can be documented as well to make it clearer for the user that only one is required (and accepted).

2023-06-28 12:20 UTC, Koodt commented on website/docs/r/fw_group_v2.html.markdown
> +* `project_id` - (Optional) The owner of the firewall group. Required if admin
I completely agree
Done

2023-06-29 07:03 UTC, nikParasyr approved these changes

2023-06-29 07:18 UTC, kayrus commented on website/docs/r/fw_group_v2.html.markdown
> +    Changing this updates the `admin_state_up` of an existing firewall group.
The status is still not removed.

2023-06-29 07:19 UTC, kayrus commented on openstack/fw_group_v2.go
> +		err := groups.Get(networkingClient, id).ExtractIntoStructPtr(&group, "firewall_group")
> return the status dynamically

not clear what exactly does it mean :\

2023-06-29 07:24 UTC, Koodt commented on website/docs/r/fw_group_v2.html.markdown
> +    Changing this updates the `admin_state_up` of an existing firewall group.
Shared was removed, not status. Lol.
Fix

2023-06-29 07:53 UTC, Koodt commented on openstack/fw_group_v2.go
> +		err := groups.Get(networkingClient, id).ExtractIntoStructPtr(&group, "firewall_group")
Understood your question.
It's V1 legacy. Align style fwGroupV2RefreshFunc with fwGroupV2DeleteFunc

2023-06-29 08:27 UTC, Koodt commented on openstack/resource_openstack_fw_group_v2.go
> +		err = groups.Update(networkingClient, d.Id(), updateOpts).Err
Done
Also for rules and policies

2023-06-29 09:03 UTC, Koodt commented
@kayrus @nikParasyr all checks have passed, all conversations was answered.
Merge?

2023-06-29 09:07 UTC, kayrus approved these changes
LGTM, thanks again fro your patience.

2023-06-29 09:08 UTC, merged

2023-06-29 09:13 UTC, kayrus commented
@Koodt are you planning to add a data source for FW groups?

2023-06-29 09:28 UTC, Koodt commented
@kayrus yes
Right now