[openstack_blockstorage_volume_v3] Create cinder volume from backup
terraform-provider-openstack/terraform-provider-openstack pull request #1637
Opened 2024-01-02 10:17 UTC by ZdenekPesek

Close: https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1636

2024-01-02 16:37 UTC, nikParasyr commented on openstack/resource_openstack_blockstorage_volume_v3.go
> +			},
Also `ForceNew: true,` should be set

2024-01-02 16:39 UTC, nikParasyr requested changes
@ZdenekPesek Hello. thanks for opening this.

Have left a couple of comments.

Moreover there should be a test case for this and also docs should be updated.

2024-01-02 16:39 UTC, nikParasyr commented on openstack/resource_openstack_blockstorage_volume_v3.go
> +		BackupID:           d.Get("backup_id").(string),
When the user has defined `backup_id` you need to set the blockstorage client microversion to 3.47

2024-01-05 10:01 UTC, kayrus commented on openstack/resource_openstack_blockstorage_volume_v3.go
> +			},
I think there should be a conflict set for all sources:
* `snapshot_id`
* `source_vol_id`
* `image_id`
* `backup_id`

2024-01-28 10:24 UTC, closed without merging