Add data source for Octavia flavors
terraform-provider-openstack/terraform-provider-openstack pull request #1651
Opened 2024-01-25 18:25 UTC by Pyjou

Close #1530

2024-01-25 18:30 UTC, nikParasyr commented
@Pyjou can you rebase to fix the conflicts?

2024-01-25 19:02 UTC, nikParasyr requested changes
Hello @Pyjou. Thanks for the PR.

Requested some changes here and there. Also rebase for the conflict. 

I'm mostly curious why ci is not triggered

2024-01-25 22:24 UTC, Pyjou commented on openstack/data_source_openstack_lb_flavor_v2_test.go
> +  name = "m1.acctest"
I think you need to create a flavor. Devstack doesn't create flavor in Octavia by default. I change the name to `lb.acctest`.
Also you need to create a flavor profile linked to the flavor.

2024-01-25 22:34 UTC, Pyjou commented
I 

> I'm mostly curious why ci is not triggered

Because the PR have conflicts ;)
Now it's fixed.

2024-01-27 17:46 UTC, nikParasyr commented
@Pyjou can you implement the CI changes from #1652? As ci fails as there is no flavor created beforehand

2024-01-28 03:30 UTC, Pyjou commented
Done. I implement the CI changes #1652

2024-01-28 09:10 UTC, nikParasyr commented on openstack/data_source_openstack_lb_flavor_v2_test.go
> +  name = "acctest"
Use the ‘osLbFlavorName’ var instead of “acctest”. Example on how: https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/b389f3bae4623195aa795dcd3c1771c338a48531/openstack/resource_openstack_compute_instance_v2_test.go#L1038

2024-01-29 10:11 UTC, nikParasyr commented
@Pyjou 1.54.0 was just released which includes a deprecation message for the `multiattach`. Since this PR (or the gophercloud bump to be exact) needs to remove support for `multiattach` then we have to make a release with a deprecation warning before we remove it. This means it will take a bit longer for this one to be released.

I'll work on a different PR to bump gophercloud and do the `multiattach` removal properly, then ill rebase this one and fix the CI here

2024-02-06 14:43 UTC, Pyjou commented
FYI, Gophercloud has released v1.9.0. And it brings the changes required for this PR. Then maybe you'll have to upgrade to this version too :)

2024-03-01 21:25 UTC, Koodt commented
Hi, folks! I need this PR too. Can i help you, or can you merge this PR? Thank you

2024-03-04 14:38 UTC, closed without merging

2024-03-04 14:43 UTC, nikParasyr commented
Ok... not sure why this was closed... I tried to rebase this PR and fix the ci, but the PR is on the `main` branch of the remote so maybe that is why? :man_shrugging: 

In any case. i created #1679 with the commit, fixed some conflicts and rebased. Also the ci.
So ill continue on the PR instead