Add support for qos_policy_id on external gateway
terraform-provider-openstack/terraform-provider-openstack pull request #1669
Opened 2024-02-02 18:34 UTC by al26p

Closes #1668

2024-02-02 20:37 UTC, kayrus requested changes
Thanks for your PR. Could you please update the documentation and fix the comments?

2024-02-02 20:37 UTC, kayrus commented on openstack/resource_openstack_objectstorage_container_v1.go
> -				Full:     true,
probably this is a mistake, please remove this.

2024-02-02 20:37 UTC, kayrus commented on openstack/resource_openstack_networking_router_v2.go
> +		gatewayInfo.QoSPolicyID = externalQoSPolicyID
I think it's enough just to assign a value directly to the `QoSPolicyID`
```suggestion
		gatewayInfo.QoSPolicyID = d.Get("external_qos_policy_id").(string)
```

2024-02-02 20:37 UTC, kayrus commented on openstack/resource_openstack_networking_router_v2.go
> +		gatewayInfo.QoSPolicyID = externalQoSPolicyID
Here as well
```suggestion
		gatewayInfo.QoSPolicyID = v
```

2024-02-02 20:37 UTC, kayrus commented on go.mod
> +	github.com/gophercloud/gophercloud v1.5.1-0.20240125150344-f7533c95474d
looks like a downgrade for me

2024-02-02 21:10 UTC, al26p commented on openstack/resource_openstack_objectstorage_container_v1.go
> -				Full:     true,
Won't compile with this. Looks like it is part of https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1660 
But yes not part of the actual update

2024-02-02 21:13 UTC, al26p commented on go.mod
> +	github.com/gophercloud/gophercloud v1.5.1-0.20240125150344-f7533c95474d
master is probably not tagged correctly but I can assure you that we are moving in the correct direction ;) 

This is linked to https://github.com/gophercloud/gophercloud/tree/f7533c95474de0ae96f4b8c8061ef790070f6899 
Should be something like 1.9.0 or 1.9.1 once it will be packaged.

2024-02-02 22:47 UTC, nikParasyr commented on go.mod
> +	github.com/gophercloud/gophercloud v1.5.1-0.20240125150344-f7533c95474d
I’m facing the same in https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1654. I think 1.9.0 was released earlier today. Ill update https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1654 early next week

2024-02-09 14:34 UTC, al26p commented
It is included in the v2 https://github.com/gophercloud/gophercloud/releases/tag/v2.0.0-beta.1 
Include is in the v2 milestone ? https://github.com/terraform-provider-openstack/terraform-provider-openstack/milestone/3

2024-02-12 23:04 UTC, al26p commented
Rebased following the closing of #1654 

Waiting for my changes in gophercloud to be released so I can point to a release instead of the commit.

2024-07-09 16:48 UTC, kayrus commented
@al26p can you rebase and fix linter errors?

2024-07-11 15:21 UTC, al26p commented
1.9 -> 1.13 Should not have impact on DNS. Perhaps it was a temporary failure ? 

Can you re-trigger the CI ?

2024-07-15 11:26 UTC, kayrus commented
@al26p thanks for the update. Could you also add functional tests? I'm not sure whether unsetting the `qos_policy_id` would make effect.

2024-07-15 20:30 UTC, al26p commented
If you unset the external_qos_policy_id it will get/use the external_qos_policy_id value returned by gophercloud. Acting like the value is not managed by terraform.

2024-07-15 20:35 UTC, kayrus commented
@al26p sounds like not good. have you tried to make the `QoSPolicyID` member as a pointer in gophercloud?

2024-07-15 20:43 UTC, al26p commented
I'm not sure I'm getting your point there. From my POV it's working as expected. 
At creation: 
- If not set: Use the default value from openstack servers
- If set: Use the set value

On update : 
- If not present: ill update the state with the value retured by openstack
- If set: Will try to update the resource according to the value specified

2024-07-15 20:54 UTC, kayrus commented
@al26p I don't have a QoS OS env right now. I can try it with devstack, but tomorrow.
Anyway, my goal is to allow unsetting the values. E.g. if you set `description = hello` it will set `description = hello`. If you omit description, the provider should unset it on next apply. If this is a gophercloud issue, let's fix it and set the `QoSPolicyID` member type to a pointer. If setting it to the pointer would case more problems, let's discuss.

Anyway, I encourage you to test with a custom gophercloud deps, where `QoSPolicyID` member is set to a pointer. Basically you can try the `go.mod` `replace`, e.g.

```
replace github.com/hophercloud/gophercloud => github.com/al26p/gophercloud %your-branch-commitid%
```

2024-07-16 11:04 UTC, kayrus commented
@al26p you need to create your own gophercloud branch from the v1 branch. We don't support v2 yet.

2024-07-16 11:13 UTC, al26p commented
Hello again ! 

I tried replacing the QoSPolicyID and the GatewayInfo by pointer on the gophercloud side to no avail. 

```
type GatewayInfo struct {
	NetworkID        string            `json:"network_id,omitempty"`
	EnableSNAT       *bool             `json:"enable_snat,omitempty"`
	ExternalFixedIPs []ExternalFixedIP `json:"external_fixed_ips,omitempty"`
	QoSPolicyID      *string           `json:"qos_policy_id,omitempty"`
}
type Router struct {
	// Status indicates whether or not a router is currently operational.
	Status string `json:"status"`

	// GateayInfo provides information on external gateway for the router.
	GatewayInfo *GatewayInfo `json:"external_gateway_info"`
...
```
It looks like the issue is broader. I observed the same behavior if I try to delete the `external_network_id` or even the `admin_state_up`.  Instead of doing something close to an `openstack router unset --external-gateway`, terraform assumes that there is no change. 

Changing the qos (or another parameter not described in the .tf) from openstack side is correctly reflected in the tfstate. 

I think it is linked to those fieds being "computed" and "optional". I don't really have fix for this. Do you have an opinion on this ? 

```
Schema: map[string]*schema.Schema{
...
	"external_qos_policy_id": {
		Type:     schema.TypeString,
		Optional: true,
		ForceNew: false,
		Computed: true,
	},
...
}
```

2024-07-16 11:15 UTC, al26p commented
@kayrus I patched by gophercloud from the v1.13.0 tag to do my tests

2024-07-22 13:14 UTC, yomovh commented
@kayrus  may be we could add the milestone 3.0.0 since this is related to  #1699  if I am not mistaken.

2024-07-22 13:26 UTC, kayrus commented
@yomovh no, it's not. however I haven't seen that PR author tried to unset the `qos_policy_id` using his custom fork. Once we confirm that we can unset the `qos_policy_id`, the fix can be proposed to gophercloud.

2024-09-22 16:06 UTC, kayrus commented
@al26p could you please rebase and make tests with the QoS policy set/unset?

2025-05-26 10:39 UTC, closed without merging