Add references between compute_servergroup and compute_instance docs
terraform-provider-openstack/terraform-provider-openstack pull request #1712
Opened 2024-05-13 22:40 UTC by jlalford

docs/resources/compute_instance_v2.md: Add reference to servergroups resource docs for instance resource attribute
docs/resources/compute_servergroup_v2.md: Add reference to instance resource attribute in overview

2024-05-14 06:40 UTC, nikParasyr requested changes

2024-05-14 06:40 UTC, nikParasyr commented on docs/resources/compute_instance_v2.md
> +    See [reference](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_servergroup_v2)
`scheduler_hints` can be used for more than just server groups. I think the reference is better put [here](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/docs/resources/compute_instance_v2.md?plain=1#L489) where it covers just server groups

2024-05-14 06:40 UTC, nikParasyr commented on docs/resources/compute_servergroup_v2.md
> +See [reference](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_instance_v2)
I would prefer instead of the reference to extend the example below with a instance resource that uses schedulers hint to use the server group. This way it will make the connection clear but also offer a code example for users

2024-05-14 18:39 UTC, jalford-ns commented on docs/resources/compute_instance_v2.md
> +    See [reference](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_servergroup_v2)
Thanks! Updated

2024-05-14 18:39 UTC, jalford-ns commented on docs/resources/compute_servergroup_v2.md
> +See [reference](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_instance_v2)
Thanks! Updated

2024-05-16 05:57 UTC, nikParasyr approved these changes
LGTM. thanks for the fixes :)

2024-05-16 06:01 UTC, merged