Add volume attach tag with nova microversion 2.49
terraform-provider-openstack/terraform-provider-openstack pull request #1713
Opened 2024-05-14 07:05 UTC by jichenjc

2024-05-14 09:03 UTC, jichenjc commented
@nikParasyr could you please help review this ? THanks

2024-05-16 06:06 UTC, nikParasyr requested changes
Thank you for this.
Some small nits on docs

2024-05-16 06:06 UTC, nikParasyr commented on docs/resources/compute_volume_attach_v2.md
> +* `tag` - (Optional) The tag of the volume attachment. Changing this
```suggestion
* `tag` - (Optional) Add a device role tag that is applied to the volume when attaching it to the VM. Changing this
```

2024-05-16 06:06 UTC, nikParasyr commented on docs/resources/compute_volume_attach_v2.md
> +    updates the tag of volume attachment. Requires microversion >= 2.49.
```suggestion
    creates a new volume attachment with the new tag. Requires microversion >= 2.49.
```

Since `ForceNew` is set below updating the tag will force a recreation of the resource.

2024-05-16 07:16 UTC, jichenjc commented
@nikParasyr thanks for the info, updated the doc accordingly

2024-05-16 08:12 UTC, nikParasyr approved these changes
LGTM

2024-05-16 08:12 UTC, merged