[networking]: add BGP VPN resources
terraform-provider-openstack/terraform-provider-openstack pull request #1738
Opened 2024-07-04 15:22 UTC by kayrus

Resolves #1666

2024-07-04 22:39 UTC, kayrus commented
@nikParasyr I also fixed the networking tests. To be honest I don't want to split this PR into multiple and waste compute resources for functional tests. But if you insist, let's split this PR.

2024-07-05 13:48 UTC, nikParasyr commented
@kayrus im fine with having it in a single one. I’m on vacation atm so I’ll be able to review it in a couple of weeks

2024-07-05 14:19 UTC, kayrus commented
@nikParasyr then I'd move the tests modifications into a separate PR and merge it to avoid issues with networking functional tests, since they're broken now.

2024-07-18 10:00 UTC, nikParasyr requested changes
@kayrus This is a first review. I didn't go through everything in full details due to the size of it.

2024-07-18 10:28 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_v2.go
> +				Type:     schema.TypeList,
Good catch. I already forgot that we had problems with this.

2024-07-18 10:42 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_v2.go
> +				Type:     schema.TypeList,
Wait, but this is a computed field.

2024-07-18 10:45 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_network_associate_v2.go
> +			"project_id": {
Same question was asked here: https://github.com/gophercloud/gophercloud/pull/3078#discussion_r1664360223
I confirmed that omitting the `project_id` in cloud admin mode causes 403 response code.

2024-07-18 10:51 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_v2.go
> +				Type:     schema.TypeList,
Yes, it's computed attribute.

2024-07-18 10:51 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_v2.go
> +				Type:     schema.TypeList,
Yes, it's computed attribute.

2024-07-18 10:52 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_v2.go
> +			"type": {
I decided to rely on neutron response, when this filed is omitted.

2024-07-18 11:01 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_network_associate_v2.go
> +	d.SetId(res.ID)
Hm, this approach is used in `blockstorage_volume_attach` and in `identity_role_assignment`, but I referred to https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/b1aec2feb9e9994fffd34d82a62a9dec9595b569/openstack/resource_openstack_lb_member_v2.go#L221
Anyway, I'll change this to `bgpvpn_id/network_association_id` once it's not recommended.

2024-07-18 11:46 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_port_associate_v2.go
> +	bgpvpnID := d.Get("bgpvpn_id").(string)
done

2024-07-18 11:46 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_router_associate_v2.go
> +	bgpvpnID := d.Get("bgpvpn_id").(string)
done

2024-07-18 11:46 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_network_associate_v2.go
> +	d.SetId(res.ID)
done

2024-07-18 11:46 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_network_associate_v2.go
> +	bgpvpnID := d.Get("bgpvpn_id").(string)
done

2024-07-18 11:46 UTC, kayrus commented on docs/resources/bgpvpn_v2.md
> +* `region` -  The region in which the BGP VPN is located.
done

2024-07-18 11:46 UTC, kayrus commented on docs/resources/bgpvpn_v2.md
> +* `vni` - (Optional) The globally-assigned VXLAN VNI for the BGP VPN.
done

2024-07-18 11:47 UTC, kayrus commented on docs/resources/bgpvpn_v2.md
> +* `type` - (Optional) The type of the BGP VPN (either `l2` or `l3`). Changing this
done

2024-07-18 14:30 UTC, nikParasyr commented on openstack/resource_openstack_bgpvpn_network_associate_v2.go
> +			"project_id": {
ok thanks. another case where api docs are not the source of truth

2024-07-18 14:38 UTC, nikParasyr commented on openstack/resource_openstack_bgpvpn_v2.go
> +				Type:     schema.TypeList,
You sure `computed` will not create an issue?

Cause if it is initially computed to:  ["a", "b"] and stored as such on the state, then on the next "Read" if neutron replies with ["b", "a"] i think it still triggers an update.

2024-07-18 14:59 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_v2.go
> +				Type:     schema.TypeList,
I've never experienced issues with this, but if you think this can prevent potential issues, let's switch to `TypeSet`.

2024-07-18 15:03 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_v2.go
> +				Type:     schema.TypeList,
Switched to `TypeSet`

2024-07-18 15:03 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_v2.go
> +				Type:     schema.TypeList,
Switched to `TypeSet`

2024-07-18 15:14 UTC, nikParasyr requested changes
Second round :).

Some doc nits and a bit more annoying the `GetOkExists` which is deprecated and can have undefined behaviors

2024-07-18 15:14 UTC, nikParasyr commented on openstack/resource_openstack_bgpvpn_port_associate_v2.go
> +	if v, ok := d.GetOkExists("advertise_fixed_ips"); ok {
Is `GetOkExists` required here? => https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1188

2024-07-18 15:14 UTC, nikParasyr commented on openstack/resource_openstack_bgpvpn_port_associate_v2.go
> +			"advertise_fixed_ips": {
Is this defaulted to true by neutron? I think it is ( based on Update on api-docs and your test below ). If it does then we can use Defualt here which should simplify the removal of GetOkExists (see below)

2024-07-18 15:14 UTC, nikParasyr commented on openstack/resource_openstack_bgpvpn_router_associate_v2.go
> +	if v, ok := d.GetOkExists("advertise_extra_routes"); ok {
https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1188

https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#ResourceData.GetOkExists

2024-07-18 15:37 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_port_associate_v2.go
> +	if v, ok := d.GetOkExists("advertise_fixed_ips"); ok {
removed

2024-07-18 15:37 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_port_associate_v2.go
> +			"advertise_fixed_ips": {
set the default value

2024-07-18 15:38 UTC, kayrus commented on docs/resources/bgpvpn_network_associate_v2.md
> +* `network_id` - (Required) The ID of the network to be associated with the BGP
fixed

2024-07-18 15:38 UTC, kayrus commented on docs/resources/bgpvpn_network_associate_v2.md
> +  associated.
fixed

2024-07-18 15:39 UTC, kayrus commented on openstack/resource_openstack_bgpvpn_router_associate_v2.go
> +	if v, ok := d.GetOkExists("advertise_extra_routes"); ok {
removed

2024-07-18 18:32 UTC, nikParasyr approved these changes
Great! Thanks for all the work and patience 😁

2024-07-18 18:38 UTC, merged