dns_recordset: fix zone ID and project ID handling for import workflows
terraform-provider-openstack/terraform-provider-openstack pull request #1778
Opened 2024-09-10 15:40 UTC by aborrero

The openstack API requires the zone ID in the API endpoint to operatate recordsets.

The project ID may be required as well because the special nature of the Designate authentication, to set the X-Auth-Sudo-Tenant-ID header.

2024-09-10 15:44 UTC, aborrero commented
I have not tested this code yet, but sharing to gather early comments.

2024-09-11 12:00 UTC, aborrero commented
I think this is ready for review now, and CI recheck.

2024-09-11 12:29 UTC, kayrus requested changes
Thanks for your PR. Please see my comments.

2024-09-11 12:29 UTC, kayrus commented on docs/resources/dns_recordset_v2.md
> +This resource can be imported by specifying the recorset ID, with optional zone ID and project ID:
```suggestion
This resource can be imported by specifying the zone ID and recordset ID with optional project ID as a prefix:
```

2024-09-11 12:29 UTC, kayrus commented on openstack/resource_openstack_dns_recordset_v2.go
> +			State: func(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
Can you define a named func and just reference it in the `StateContext` value?

2024-09-11 12:48 UTC, aborrero commented on docs/resources/dns_recordset_v2.md
> +This resource can be imported by specifying the recorset ID, with optional zone ID and project ID:
done!

2024-09-11 12:48 UTC, aborrero commented on openstack/resource_openstack_dns_recordset_v2.go
> +			State: func(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
done!

2024-09-11 13:11 UTC, kayrus approved these changes

2024-09-11 13:39 UTC, kayrus reviewed
Thanks. Looks good. I have a couple of nits. Once done, I think it's ok to merge.
cc @nikParasyr

2024-09-11 13:39 UTC, kayrus commented on docs/resources/dns_recordset_v2.md
> +This resource can be imported by specifying the zone ID and recordset ID with optional project ID as a prefix:
```suggestion
This resource can be imported by specifying the zone ID and recordset ID with an optional project ID as a prefix:
```

2024-09-11 13:39 UTC, kayrus commented on openstack/resource_openstack_dns_recordset_v2.go
> +func resourceDNSRecordSetV2Import(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
can you move this func at the end?

2024-09-11 15:44 UTC, aborrero commented on docs/resources/dns_recordset_v2.md
> +This resource can be imported by specifying the zone ID and recordset ID with optional project ID as a prefix:
done!

2024-09-11 15:44 UTC, aborrero commented on openstack/resource_openstack_dns_recordset_v2.go
> +func resourceDNSRecordSetV2Import(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
done!

2024-09-12 17:01 UTC, nikParasyr approved these changes

2024-09-12 17:01 UTC, merged