feat: add openstack_workflow_v2 datasource
terraform-provider-openstack/terraform-provider-openstack pull request #1813
Opened 2024-11-01 22:09 UTC by anthonyroussel

2024-11-04 19:56 UTC, anthonyroussel commented
Bobcat Mistral workflow is failing and I don't understand why yet:

```console
 Nov 04 19:53:52 fv-az1490-394 mistral-server[71449]: 2024-11-04 19:53:52.089 71449 ERROR oslo_service.service     raise exceptions.Etcd3Exception(resp.text, resp.reason)
Nov 04 19:53:52 fv-az1490-394 mistral-server[71449]: 2024-11-04 19:53:52.089 71449 ERROR oslo_service.service etcd3gw.exceptions.Etcd3Exception: Not Found
Nov 04 19:53:52 fv-az1490-394 mistral-server[71449]: 2024-11-04 19:53:52.089 71449 ERROR oslo_service.service 
Nov 04 19:53:52 fv-az1490-394 mistral-server[71449]: 2024-11-04 19:53:52.090 71449 INFO mistral.engine.engine_server [-] Stopping an engine server [graceful=True, timeout=60]
```

See https://github.com/anthonyroussel/terraform-provider-openstack/actions/runs/11671350585/job/32498046218

2024-11-08 23:12 UTC, anthonyroussel commented
## Failing 2023.2 Mistral pipeline
Fixed the Mistral pipeline by integrating these 2 patches for the 2023.2 (bobcat) workflow:
* https://github.com/openstack/mistral/commit/e343ccb078d8ba261ac70afca93f4358589730d3
* https://github.com/openstack/mistral/commit/ecdeadeb7a1aa87cba2cdb0c1a2bb1ffc4aabf25

Mistral Devstack's plugin version has been set to commit `ecdeadeb7a1aa87cba2cdb0c1a2bb1ffc4aabf25` (stable/2023.2 + release commit + these 2 patches) for the Mistral workflow.

## Gophercloud PR
The gophercloud/utils PR to add the WorkflowV2Client to utils has been merged, see https://github.com/gophercloud/utils/pull/234

2024-11-11 06:16 UTC, nikParasyr requested changes
Hello. Thanks for working on this.
First review, ill need to go through some stuff again as it is quite a big PR.
Some changes requested already.

Some notes/questions:
- data source should be named `openstack_workflow_workflow_v2`. While this might feel duplication the convention is `cloud/provider_serviceName_resourceName, and we shouldnt break it
- would like input from @kayrus as well in general
- @anthonyroussel are you intending to work on more data-sources/resources of mistral? Would be good if we get an issue with all the data-sources/resources to keep track of progress.

2024-11-11 06:16 UTC, nikParasyr commented on .github/workflows/functional-workflow.yml
> +          - name: "antelope"
Can you remove `antelope`? In general we support 3 latest + master, do with dalmatian in, antelope should be out.

2024-11-11 06:16 UTC, nikParasyr commented on docs/data-sources/workflow_v2.md
> +* `project_id` - (Optional) The id of the project to retrieve the workflow.
Doesn't defining this require admin credentials? if so, please document it.

2024-11-11 06:16 UTC, nikParasyr commented on openstack/data_source_openstack_workflow_v2.go
> +				Optional: true,
From my understanding, this cannot be set by the user, thus `Optional` should be removed and only computed left.

2024-11-11 06:16 UTC, nikParasyr commented on openstack/data_source_openstack_workflow_v2.go
> +				Optional: true,
From my understanding, this cannot be set by the user, thus `Optional` should be removed and only computed left.

2024-11-11 06:16 UTC, nikParasyr commented on openstack/data_source_openstack_workflow_v2.go
> +				Optional: true,
From my understanding, this cannot be set by the user, thus `Optional` should be removed and only computed left.

2024-11-11 06:16 UTC, nikParasyr commented on openstack/data_source_openstack_workflow_v2.go
> +				Optional: true,
From my understanding, this cannot be set by the user, thus `Optional` should be removed and only computed left.

2024-11-11 06:16 UTC, nikParasyr commented on openstack/data_source_openstack_workflow_v2.go
> +				Optional: true,
From my understanding, this cannot be set by the user, thus `Optional` should be removed and only computed left.

2024-11-11 06:16 UTC, nikParasyr commented on openstack/provider.go
> +			"openstack_workflow_v2":                              dataSourceWorkflowV2(),
This should be `openstack_workflow_workflow_v2`

2024-11-11 15:57 UTC, anthonyroussel commented
Hello @nikParasyr, and thanks for the review!

> data source should be named openstack_workflow_workflow_v2. While this might feel duplication the convention is `cloud/provider_serviceName_resourceName, and we shouldnt break it

Sure! I've modified the datasource name to openstack_workflow_workflow_v2.

> are you intending to work on more data-sources/resources of mistral? Would be good if we get an issue with all the data-sources/resources to keep track of progress.

Yes, I plan to work on additional Mistral resources and datasources. I created issue #1818 to track the progress on the Mistral implementation in the provider.

2024-11-11 15:58 UTC, anthonyroussel commented on .github/workflows/functional-workflow.yml
> +          - name: "antelope"
I removed antelope from build matrix.

2024-11-11 15:58 UTC, anthonyroussel commented on openstack/provider.go
> +			"openstack_workflow_v2":                              dataSourceWorkflowV2(),
Sure, I renamed the datasource to openstack_workflow_workflow_v2.

2024-11-11 15:59 UTC, anthonyroussel commented on openstack/data_source_openstack_workflow_v2.go
> +				Optional: true,
Yes you're right, I removed the `Optional` and keep the `Computed` only for these fields.

2024-11-15 07:36 UTC, merged